"""Baut data/huette.json: die Ordnung der Steinmetzen, beschlossen auf dem Tag zu Regensburg 1459,
nach dem Straßburger Hüttenbuch bei Heideloff.

Frühneuhochdeutsch: Carl Alexander Heideloff, Die Bauhütte des Mittelalters in Deutschland
(Nürnberg 1844), Beilage Nro. 1 „Ordenunge der Steinmetzen zu Strasburg 1459“, S. 34–42.
Internet Archive 10048396bsb (Digitalisat der Bayerischen Staatsbibliothek); Seite 34 = Blatt 53,
fortlaufend. In Fraktur gesetzt; am Seitenbild gelesen, die maschinelle Texterkennung diente nur
der Orientierung und war an mehreren Stellen falsch. Heideloffs Schreibung und seine Absatzbuchstaben
sind beibehalten; seine erklärenden Zusätze in runden Klammern (etwa „wer (wäre) es“) sind weggelassen.
Übersetzung: eigene Arbeitsübersetzung (CC0).
"""
import json
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "data" / "huette.json"

ORDNUNG = [
    dict(n=1, titel="Im Namen der Vier Gekrönten", pg="34", lang="fnhd",
         orig="In Namen des Vaters, des Suns und des Heiligen Geists und der würdigen Mutter Marien und auch ir seligen Diener, der Heiligen Vier gekrönten zu ewiger Gedechtnisse. angesehen, daß rechte Früntschaft, Einhelligkeit und Gehorsamkeit ist ein Fundament alles gutten; darumb und durch gemeynen nutz und freuen Willen aller Fürsten, Grofen, Herren, Stetten, Stifter und Klöstern, die Kirchen, Cöre oder ander große Steynwerk und Gebäue yetz machent oder in künftigen zitten machen möchtend: das die dastebas versorget und versehen werdent, und auch umb nutz und Nothdurfft willen aller Meister und Gesellen des gantzen Hantwercks des Steynwercks und Steinmetzen in dütschen Landen, und besonder zu versehen zwüschent denselben des Hantwercks künftige zweytrachten, myssehelle, Kumber, Costen und Schaden, die den ettelicher unordentlicher Handelunge halb under ettelichen Meistern schedelich gelitten und schwerlich gewesen sind wider soliche gutte Gewohnheit und alt herkommen, so ihr altforden und liebhaber des Hantwercks vor alten zitten In gutter meynunge gehenthabt und harbrocht habent, Aber darine im rechten frydelich wegen zu suchen und fürbaß zu bliben; So hant Wür Meister und Gesellen desselben Hantwercks alle, die dann in Kapittels wise by einander gewesen sint zu Spyr, zu Straßburg und Regensburg im namen und anstatt unser und aller ander Meister und Gesellen unsers gantzen gemeinen Hantwercks obgemeldet, Solich alt Harkumen ernüwert und geluttert, und Uns diser Ordenunge und Brüderschaft gietlich und freyntlich vereynt, und die einhelleklich uffgesetzet, auch gelobt und versprochen für uns und alle unsere Nochkümmen getrüwelich zu halten, also hirnach geschrieben stett:",
         en="Im Namen des Vaters, des Sohnes und des Heiligen Geistes und der würdigen Mutter Maria und auch ihrer seligen Diener, der heiligen Vier Gekrönten, zu ewigem Gedächtnis. In Anbetracht dessen, dass rechte Freundschaft, Einigkeit und Gehorsam ein Fundament alles Guten sind, darum und um des gemeinen Nutzens und des freien Willens aller Fürsten, Grafen, Herren, Städte, Stifte und Klöster willen, die jetzt Kirchen, Chöre oder andere große Steinwerke und Gebäude machen oder in künftigen Zeiten machen möchten, damit diese desto besser versorgt und versehen werden; und auch um des Nutzens und der Notdurft aller Meister und Gesellen des ganzen Handwerks des Steinwerks und der Steinmetzen in deutschen Landen willen, und besonders, um unter denselben vom Handwerk künftigen Zwietracht, Missstimmung, Kummer, Kosten und Schaden vorzubeugen, die wegen manchen unordentlichen Handelns unter manchen Meistern schädlich erlitten worden und schwer gewesen sind, gegen die gute Gewohnheit und das alte Herkommen, das ihre Vorfahren und die Liebhaber des Handwerks vor alten Zeiten in guter Meinung gehandhabt und hergebracht haben, vielmehr darin im Recht friedliche Wege zu suchen und fernerhin dabei zu bleiben: So haben wir Meister und Gesellen desselben Handwerks alle, die wir in der Weise eines Kapitels zu Speyer, zu Straßburg und zu Regensburg beieinander gewesen sind, im Namen und anstatt unser und aller anderen Meister und Gesellen unseres ganzen gemeinen Handwerks, solches alte Herkommen erneuert und geläutert und uns dieser Ordnung und Bruderschaft gütlich und freundlich geeinigt, und sie einhellig aufgesetzt, auch gelobt und versprochen, für uns und alle unsere Nachkommen getreulich zu halten, wie hiernach geschrieben steht:",
         note="Die Vier Gekrönten (Quattuor Coronati) waren nach der Legende Steinmetzen, die sich unter Diokletian weigerten, ein Götterbild zu hauen, und dafür hingerichtet wurden; sie waren die Patrone der Bauhütten. Die Ordnung nennt als Zweck an erster Stelle den Nutzen der Bauherren, ‚Fürsten, Grafen, Herren, Städte, Stifte und Klöster‘, und erst dann den der Meister und Gesellen. Heideloff druckt den Text nach dem Straßburger Hüttenbuch, mit Einträgen bis in die 1470er Jahre; beschlossen wurde die Ordnung auf dem Tag zu Regensburg am Markustag, dem 25. April 1459 (Hütte [15])."),
    dict(n=2, titel="Was zu hart ist, darf man mildern", pg="34–35", lang="fnhd",
         orig="a) Zum Ersten: wer es, das ettelicher Artikel in dieser Ordnunge zu schwer und zu herte, oder ettelicher zu lichte und zu mylte werent; Do mögent die, die in dieser Ordenunge sint, mit dem merenteyl soliche Artikel myltern, mynern oder meren, je noch der zitt und des Lands notdurfft und nach den Laiffen. Die dan in Kapittels wise, so ein berüfunge ist, by em andersint noch Innhalt dis Buchs: das sol dan aber für usgehalten werden, by der Glübde, die ein jeglicher globt hett. b) Item: wer mit guttem willen in dise Ordenunge will, nach Ordenunge also hie noch in disem Buch geschrieben stott; der soll alle Punkten und Artikel globen zu halten, der unsers Hantwercks ist des Steinwercks. Das sollent die Meyster sin, die soliche köstliche Bäüe und Werk könnent und machent, do sie uff gefryget sind, und mit keinem Handwerk dienent, sie woltend es den gern tun. Es siend Meister oder gesellen; umb daß sie sich auch haltend sollent und miessen den Eren noch, und niemans von Inen verkürtzet werden, un man auch dieselben darumb in der Ordenunge macht abzustraffen nach Gelegenheit einer jeglichen Handelunge.",
         en="a) Zum Ersten: Wäre es, dass mancher Artikel in dieser Ordnung zu schwer und zu hart oder mancher zu leicht und zu milde wäre, so mögen die, die in dieser Ordnung sind, mit der Mehrheit solche Artikel mildern, mindern oder mehren, je nach der Zeit und der Notdurft des Landes und nach den Läuften, sooft sie in der Weise eines Kapitels, wenn eine Zusammenberufung ist, beieinander sind, nach dem Inhalt dieses Buches; das soll dann aber fortan gehalten werden, bei dem Gelübde, das ein jeder gelobt hat. b) Item: Wer mit gutem Willen in diese Ordnung will, nach der Ordnung, wie sie hiernach in diesem Buch geschrieben steht, der soll geloben, alle Punkte und Artikel zu halten, wenn er von unserem Handwerk des Steinwerks ist. Das sollen die Meister sein, die solche kostbaren Bauten und Werke können und machen, für die sie freigestellt sind, und die keinem Handwerk dienen, es sei denn, sie wollten es gern tun. Es seien Meister oder Gesellen: damit sie sich auch nach der Ehre halten sollen und müssen und niemand von ihnen verkürzt werde, und damit man sie auch in der Ordnung bestrafen kann, je nach Lage einer jeden Handlung.",
         note="Die Ordnung ist änderbar, mit Mehrheit, auf einem Kapitel; das ist eine Verfassung, kein Gesetz von oben. Mitglieder sind die Meister ‚köstlicher‘ Bauten, die ‚mit keinem Handwerk dienen‘, also keiner städtischen Zunft angehören: genau das Recht, das Ulrich von Ensingen 1402 in Straßburg für seine Steinmetzen gegen die Maurerzunft erstritt (Ensingen Straßburg [3])."),
    dict(n=3, titel="Im Taglohn, nicht verdingt", pg="35", lang="fnhd",
         orig="c) Item: was redelicher werk und Gebeue nu zu zittern sind, die in Tagelon stoat, nemlich also: Stroßburg, Cöln und Wien und Passauwe und ander Werk derglichen, und in den Hütten, so dazu gehörent, also herkommen sint und vollbracht untzhar In Tagelon: Dieselben Beue und Werk, also vorstott, sol man also lassen bliben in Tagelon und kein verdinget Werk daraus nit machen in geheynen wegk, umb daß dem Werk von der gedinge wegen mit abgebrochen werde, also verne es an im stott.",
         en="c) Item: Welche ordentlichen Werke und Bauten jetzt zu Zeiten im Taglohn stehen, nämlich Straßburg, Köln und Wien und Passau und andere Werke dergleichen, und in den Hütten, die dazu gehören, wie es herkömmlich ist und bisher im Taglohn vollbracht wurde: Dieselben Bauten und Werke, wie vorsteht, soll man im Taglohn bleiben lassen und auf keinen Fall ein verdingtes Werk daraus machen, damit dem Werk nicht wegen des Gedinges etwas abgebrochen werde, soweit es an ihm steht.",
         note="‚Verdingt‘ heißt: zu einem festen Preis vergeben, im Akkord. Die Hütten der großen Dome sollen im Taglohn bleiben, weil ein Meister, der zum Festpreis baut, am Werk spart: ‚damit dem Werk nichts abgebrochen werde‘. Ulm steht nicht in der Liste, aber der Ulmer Vertrag von 1392 zahlte den Meister ebenfalls nach der Zeit, einen Gulden die Woche (Ensingen Ulm [1]). Fabris Klage über die ‚parvifici‘, die am Schmuck sparen (Fünf Werke [2]), beschreibt die Gefahr, gegen die dieser Artikel steht."),
    dict(n=4, titel="Wenn der Meister stirbt", pg="35", lang="fnhd",
         orig="d) Item: wer es auch: daß ein Werkmann, der ein Redelich Werk Inne hat, von Tod abgienge; so mag ein jeglich Werkmann oder ein Meister, der sich dan Steinwerks verstott und dem Werk gnüg und datzu Dauwelich ist, noch einem solichem Werk wohl ston und werben, uff daß die Herrn, die solich Werk und Beue Inhends hant und verwaltend, wieder versorget werdent noch des Steinwerks Notdurfft. Desgleichen mag ein jegelicher Geselle auch tun, der sich umb solich Steinwerk verstott. [...] f) Item: Wan ein Meister, wer der were, der solich vorgemeldet Werk und Gebeue Inhends und besessen hett, von Tod abget, und ein ander Meister, der kumet und gehauwen Steinwerks do findet, Es wer versetzet oder unversetzet steinwerk: do sol der selb Meister semlich versetzet steinwerk nit wider abheben, noch das gehawen unversetzet Steinwerk nit verwerfen In geheinen wegk on ander werklitt rott und erkennen, uff daß die Herren und ander erbar litte, die solich Beue machen lossent, nie zu unredelichem Costen kument, und auch der Meister, der solich Werk noch Tode gelossen hett, nit geschmehet werde. wolltend aber die Hern solich Werk abheben lassen, das mag er lossen gescheen, so verne daß er kein geverde dar Inne suche.",
         en="d) Item: Wäre es auch, dass ein Werkmann, der ein ordentliches Werk innehat, durch den Tod abginge, so mag jeder Werkmann oder Meister, der sich auf das Steinwerk versteht und dem Werk gewachsen und dazu tauglich ist, sich um ein solches Werk wohl bemühen und bewerben, damit die Herren, die solches Werk und solche Bauten in Händen haben und verwalten, wieder versorgt werden nach der Notdurft des Steinwerks. Desgleichen mag jeder Geselle tun, der sich auf solches Steinwerk versteht. [...] f) Item: Wenn ein Meister, wer er auch sei, der ein solches vorgemeldetes Werk und solchen Bau in Händen und besessen hatte, durch den Tod abgeht, und ein anderer Meister kommt und gehauenes Steinwerk dort findet, es sei versetztes oder unversetztes Steinwerk, so soll derselbe Meister solches versetzte Steinwerk nicht wieder abheben und das gehauene, unversetzte Steinwerk auf keinen Fall verwerfen ohne Rat und Urteil anderer Werkleute, damit die Herren und andere ehrbare Leute, die solche Bauten machen lassen, nicht zu unredlichen Kosten kommen und auch der Meister, der solches Werk nach seinem Tod hinterlassen hat, nicht geschmäht werde. Wollten aber die Herren solches Werk abheben lassen, so mag er es geschehen lassen, sofern er keine Arglist darin sucht.",
         note="Zwei Artikel über die Nachfolge, das Gerüst der Generationenfolge im Spiel: Stirbt der Meister, darf sich jeder Taugliche bewerben, auch ein Geselle; und der Nachfolger darf nicht abreißen, was der Vorgänger gesetzt hat, ohne das Urteil anderer Werkleute. Geschützt werden zwei: die Bauherren vor unnötigen Kosten und der tote Meister vor der Schmähung. Das letzte Wort haben aber die Herren: Wollen sie abbrechen, wird abgebrochen. Ausgelassen ist Artikel e) über Nebenwerke des Meisters."),
    dict(n=5, titel="Nach der Visierung bauen", pg="36", lang="fnhd",
         orig="i) Es sollent auch nit zwey Meister ein Werk oder einen Gebeue gemein mit einander haben; Es wer den, daß es ein kleiner Gebeuwe were, der In Jorsfryst ein ende näme ungeverlich; den mag man wol gemeyn haben mit dem, der ein mytbruder ist. k) Item: wen ein jeglich Meister ein Werk verdinget und ein Vysierunge dazu git, wie das werden so: dem Werk sol er nit abbrechen an der Vysierunge, Sunder er sol es machen, wie er die Vysierunge den hern, Stetten oder im Lande gezeiget hett, also, daß es nit geschwechet werde.",
         en="i) Es sollen auch nicht zwei Meister ein Werk oder einen Bau gemeinsam miteinander haben, es sei denn, es wäre ein kleiner Bau, der binnen Jahresfrist ungefähr ein Ende nähme; den mag man wohl gemeinsam haben mit einem, der ein Mitbruder ist. k) Item: Wenn ein Meister ein Werk verdingt und eine Visierung dazu gibt, wie es werden soll, so soll er dem Werk an der Visierung nichts abbrechen, sondern er soll es machen, wie er die Visierung den Herren, den Städten oder im Land gezeigt hat, so dass es nicht geschwächt werde.",
         note="Die ‚Visierung‘ ist der Bauriss, die Zeichnung, nach der gebaut wird. Was der Meister dem Bauherrn gezeigt hat, muss er bauen: Er darf nicht nachträglich am Plan sparen. Das ist dieselbe Sorge, die Fabri 1488 in Ulm ausspricht, nur umgekehrt verteilt: Bei Fabri sind es die Heutigen, die hinter dem Plan der Gründer zurückbleiben (Fünf Werke [2]); hier ist es der Meister, den die Ordnung an seinen eigenen Plan bindet."),
    dict(n=6, titel="Keinen vom Werk drängen", pg="36", lang="fnhd",
         orig="l) Wer der ist, er sige Meister oder Geselle, der einem andern Meister, der in diser Ordenunge der Werklitt ist und ein Werk Inne hatt, also von demselben Werk gestrenget wurt, oder eime noch sinem Werk stellet, heimlich oder öffentlich, on desselben Meisters Wissen oder Willen, der dosselb Werk also besitzet, Es sige klein oder groß: derselb der sol fürgenumen werden, und sol auch kein Meister oder Geselle kein gemeinschaft mit Im haben, und sol auch kein Geselle, der in der Ordenunge ist, in sin fürderunge nit ziehen, die wyle er daselb Werk besitzet, daß er also unredelich zu seinen handen brocht hett, also lang, byß daß dem, der also von dem Werk getrengt wurt, einkehrunge und ein beniegen beschicht, und auch gestrofft wurt in der Ordenunge von den Meistern, den das von der Ordenunge wegen befohlen wurt.",
         en="l) Wer es auch sei, Meister oder Geselle, der einen anderen Meister, der in dieser Ordnung der Werkleute ist und ein Werk innehat, von diesem Werk verdrängt oder ihm nach seinem Werk trachtet, heimlich oder öffentlich, ohne Wissen oder Willen des Meisters, der dieses Werk besitzt, es sei klein oder groß: Der soll vorgenommen werden, und kein Meister oder Geselle soll Gemeinschaft mit ihm haben, und kein Geselle, der in der Ordnung ist, soll in seinen Dienst gehen, solange er dieses Werk besitzt, das er so unredlich an sich gebracht hat, so lange, bis dem, der so vom Werk verdrängt wurde, Wiedergutmachung und Genüge geschieht und jener in der Ordnung von den Meistern bestraft wird, denen das von der Ordnung wegen befohlen ist.",
         note="Die Strafe ist der Boykott: Kein Geselle der Bruderschaft arbeitet für den, der einem anderen das Werk abgejagt hat. Was die Ordnung nicht regeln kann, ist der Fall, dass der Bauherr selbst den Meister entlässt; das blieb, wie der Ulmer Vertrag von 1392 zeigt, Sache des Rats (Ensingen Ulm [2])."),
    dict(n=7, titel="Kein unwissender Meister, keine Lehre um Geld", pg="36", lang="fnhd",
         orig="m) Item: wer es auch, daß sich geheiner, wer der were, steinwerks us massen oder von uszuge ennemmen wolte, das er sich nit verwuste, us de grunde zu nemen, und der auch keinem Werkmann darumb gedient, noch sich Hütte fürderung nit gebrucht hett; der soll sich der Stück nüt annemen, in keinem Wegk. Wolte sich aber einer soliches underziehen; so sol kein Geselle nit by Im stan, noch in sin fürderung nit ziehen, umb daß die Hern nit zu untzimlichen costen kument durch einen solichen unwissenen Meister. [...] o) Es sol kein Werkmann noch Meister von keinem Gesellen kein Gelt nemen, das er ihn etwas lere oder wiese, das Steinwerk berieren ist. Desselben glichen sol auch kein Parlierer oder Geselle keinen umb Gelt wiesen oder leren, In massen vorstott. Will aber einer dem andern ettewas underwissen oder leren; das mögent sie wol tun, ein Stück umb das ander oder umb Gesellen Willen.",
         en="m) Item: Wäre es auch, dass einer, wer er auch sei, sich unterfangen wollte, Steinwerk nach Maßen oder nach einem Auszug zu machen, und der nicht verstünde, es aus dem Grund zu nehmen, und der auch keinem Werkmann darum gedient und keinen Hüttendienst getan hätte, der soll sich solcher Stücke auf keinen Fall annehmen. Wollte sich aber einer dessen unterziehen, so soll kein Geselle bei ihm stehen noch in seinen Dienst gehen, damit die Herren nicht durch einen solchen unwissenden Meister zu ungebührlichen Kosten kommen. [...] o) Kein Werkmann oder Meister soll von einem Gesellen Geld nehmen, dafür dass er ihn etwas lehre oder weise, was das Steinwerk betrifft. Ebenso soll kein Parlier oder Geselle einen um Geld weisen oder lehren, wie vorsteht. Will aber einer dem anderen etwas unterweisen oder lehren, so mögen sie das wohl tun, ein Stück gegen das andere oder aus Gesellenfreundschaft.",
         note="‚Aus dem Grund nehmen‘ ist die Kunst, aus dem Grundriss die Aufrisse und Werkstücke abzuleiten; wer nur nach fremden Maßen oder einem ‚Auszug‘ arbeitet, gilt als ‚unwissender Meister‘. Das ist das Geheimnis, von dem der Ulmer Vertrag spricht, wenn er Ulrich verpflichtet, den Pflegern ‚heimliche und verborgene Sachen‘ zu erklären (Ensingen Ulm [4]). Das Wissen wird nicht verkauft, nur getauscht. Artikel n) ist ausgelassen."),
    dict(n=8, titel="Drei Diener, nicht mehr als fünf", pg="36", lang="fnhd",
         orig="p) Item: Welicher Meister ein Werk oder einen Gebeue allein hett: der mag dry gediener haben, da er auch Gesellen uff gefürdere magk uff derselben hütten, magk er das anders an sinen öbern haben. hett er aber me Beue, den einen; so soll er den nit me den zwey diener haben uff dem vorgemeldeten Beue, also, daß er über fünf Diener nit haben sol uf allen seinen Beuen.",
         en="p) Item: Welcher Meister ein Werk oder einen Bau allein hat, der mag drei Diener haben, wenn er auch Gesellen auf derselben Hütte beschäftigen kann, sofern er es bei seinen Oberen anders haben kann. Hat er aber mehr Bauten als einen, so soll er nicht mehr als zwei Diener auf dem vorgemeldeten Bau haben, so dass er auf allen seinen Bauten nicht über fünf Diener haben soll.",
         note="‚Diener‘ sind die Lehrlinge. Die Zahl ist begrenzt, damit die Meister nicht mit billigen Lehrlingen statt mit Gesellen bauen. Der Ulmer Rat war 1392 strenger als die Bruderschaft 1459: Ulrich von Ensingen durfte ‚nicht mehr als zwei Lehrknaben‘ haben (Ensingen Ulm [2])."),
    dict(n=9, titel="Wer beichtet, wer spielt, mit wem er lebt", pg="36–37, 39", lang="fnhd",
         orig="Item: Man soll auch keinen Meister oder Werkmann nit in die Ordenunge empfangen, der also nit Jors zu dem heiligen Sakrament ginge, oder nit Christenliche Ordenunge hielte, oder das sine verspielte. Oder were es, daß einer ungeverlich in die ordenunge empfangen wurde, der sölichs däte, also vorstott: mit dem sol kein Meister kein Geselleschaft han, und sol auch kein Geselle by ime ston, so lange untz daß er davon lasset und von den, die in der Ordenunge sint, gestroffet wurt. [...] Dis ist die Ordenunge der Palierer und Gesellen. Item: Es sol kein Werkmann oder Meister keinen Gesellen me fürdern, der ein Frauwe mit Ime fiert zu der Unee, oder offentlich fiert ein unredlich Leben mit Frauwen, oder der Jerlich nit Bichtet und nit zu dem heiligen Sacrament ginge nach Christenlicher Ordenunge, noch auch einen solicher, der veruchet ist, daß er sin Kleider verspylt.",
         en="Item: Man soll auch keinen Meister oder Werkmann in die Ordnung aufnehmen, der nicht jährlich zum heiligen Sakrament ginge oder nicht christliche Ordnung hielte oder das Seine verspielte. Oder wäre es, dass einer ohne Arglist in die Ordnung aufgenommen würde, der solches täte, wie vorsteht: Mit dem soll kein Meister Gesellschaft haben, und kein Geselle soll bei ihm stehen, so lange, bis er davon lässt und von denen, die in der Ordnung sind, bestraft wird. [...] Dies ist die Ordnung der Parliere und Gesellen. Item: Kein Werkmann oder Meister soll einen Gesellen mehr beschäftigen, der eine Frau in unehelicher Gemeinschaft mit sich führt oder öffentlich ein unredliches Leben mit Frauen führt, oder der nicht jährlich beichtet und nicht zum heiligen Sakrament geht nach christlicher Ordnung, noch einen solchen, der dafür verrufen ist, dass er seine Kleider verspielt.",
         note="Die Bruderschaft ist auch eine Sittenordnung, und sie schließt aus: wer nicht beichtet, wer spielt, wer mit einer Frau ohne Ehe lebt. Die Frau selbst kommt in der ganzen Ordnung nur so vor, als Grund, einen Gesellen nicht zu beschäftigen; Frauen arbeiteten nach der neueren Literatur auf mittelalterlichen Baustellen als Taglöhnerinnen, in der Bruderschaft der Steinmetzen hatten sie keinen Platz. Ausgelassen ist der Artikel gegen Meister, die öffentlich ‚zu der Unee sitzen‘."),
    dict(n=10, titel="Gehorsam, und kein Schelten auf das Werk", pg="37–38", lang="fnhd",
         orig="s) Es sol auch ein jeglicher Parlierer sinen Meister in Ehren halten, ihm gewillig und gehorsam zum sin, nach Steinwerks recht, und ihn mit gantzen Trauen meynen, als billig und harkumen ist. Desglichen sol ein Geselle auch tun. Und wan auch einem wandel Gesellen gebürt fürter zu wandeln; So solent sie in solicher massen scheiden von Ihrem Meister und von den Hütten, also daß sie niemans schuldig blibent und gegen aller menschlichem unklaghaft sient, also billig ist. t) Item: Ein jeglich wandel Geselle, uff welcher Hütte der gefürdet wert, sol seinem Meister und dem Parlierer gehorsam sin nach Steinwerks recht und harkumen, und sol auch alle Ordenunge und Fryheit halten, die uff derselben hütten von alter Herkumen sint. Und sol auch dem Meister sin Werk nit schelten heimlich noch offenlich in Geheinen Wegk; Es wer dan, daß der Meister in dise Ordenunge griffe und do wider döte: das mag ein jeglicher von Ime sagen.",
         en="s) Es soll auch jeder Parlier seinen Meister in Ehren halten, ihm willig und gehorsam sein nach Steinmetzrecht und ihm mit ganzer Treue zugetan sein, wie es billig und herkömmlich ist. Desgleichen soll ein Geselle auch tun. Und wenn es einem wandernden Gesellen gebührt, weiterzuwandern, so sollen sie in solcher Weise von ihrem Meister und von den Hütten scheiden, dass sie niemandem etwas schuldig bleiben und gegen alle Menschen ohne Klage sind, wie es billig ist. t) Item: Jeder wandernde Geselle, auf welcher Hütte er auch beschäftigt wird, soll seinem Meister und dem Parlier gehorsam sein nach Steinmetzrecht und Herkommen und soll auch alle Ordnungen und Freiheiten halten, die auf derselben Hütte von alters herkommen. Und er soll dem Meister sein Werk nicht schelten, weder heimlich noch öffentlich, auf keine Weise; es sei denn, der Meister griffe in diese Ordnung ein und täte dagegen: Das mag dann jeder von ihm sagen.",
         note="Der Parlier ist der Stellvertreter des Meisters auf der Baustelle, den er ‚auch in der Zeit der Abwesenheit vertrat‘, wie Carstanjen (1893, S. 12) schreibt. Das Verbot, das Werk des Meisters zu schelten, schützt seinen Ruf beim Bauherrn: Ein Geselle, der herumerzählt, das Gewölbe sei schlecht, kann den Meister die Stelle kosten. 1492 fielen in Ulm Steine, und der Meister verließ nach der neueren Literatur die Stadt; ob Gesellen vorher gewarnt hatten, sagen die Quellen dieses Apparats bisher nicht."),
    dict(n=11, titel="Das Buch, das man nicht abschreiben darf", pg="38", lang="fnhd",
         orig="z) Item: welicher Meister auch der Biecher eins hinder Ime hett, der sol by der Glübde der Ordenunge das Buch versorgen, daß dz weder durch ihn oder jemanns anders usgeschriben, geben oder geliehen werde, umb daß die Biecher by ihren crefften blibent, wie das die wercklütte beschliessent. Aber wer jemans, der in der Ordenunge ist, eins Artickels oder zweyger notdürftig ungverlich: das mag ihm ein jeglicher Meister wol geschriben geben, und sol auch der selb Meister alle jor dise Ordenunge den Gesellen uff den Hütten losen vorlesen.",
         en="z) Item: Welcher Meister auch eines der Bücher bei sich hat, der soll bei dem Gelübde der Ordnung das Buch verwahren, dass es weder durch ihn noch durch jemand anderen abgeschrieben, weggegeben oder geliehen werde, damit die Bücher bei ihrer Kraft bleiben, wie es die Werkleute beschließen. Wäre aber jemand, der in der Ordnung ist, eines Artikels oder zweier bedürftig, so mag ihm jeder Meister das wohl schriftlich geben; und derselbe Meister soll auch jedes Jahr diese Ordnung den Gesellen auf den Hütten vorlesen lassen.",
         note="Das Buch ist zugleich geheim und öffentlich: Es darf nicht abgeschrieben werden, aber es wird jedes Jahr auf jeder Hütte, die eines hat, den Gesellen vorgelesen. Die Haupthütten, die ein Buch besaßen, waren die Gerichtsorte der Bruderschaft (Hütte [12] und [15]). Heideloff druckt es 1844, und das ist die Ironie seines Buches: Das Geheimnis der Hütten wurde zum Gegenstand der romantischen Gotikbegeisterung, in der im selben Jahr 1844 auch in Ulm wieder gebaut wurde."),
    dict(n=12, titel="Die Büchse", pg="39", lang="fnhd",
         orig="2) Alle Meister und Wercklütte, die in diser Ordenunge sint, die dan Hütten fürderungen hant, sol jeglicher eine Büchse han, und sol jeglicher Geselle alle Wuche einen Pfenninge in die Büchse geben, und sol derselb Meister dasselb Geld und was Just gefellet, in die Büchse getruwelich samlen und Jors in die Ordenunge antwurten, do dz nechste Buch lytt, Gottesdienst domit zu fürdern und unser Notdurfft der Ordenunge zu versehn. [...] 5) Wer es auch, daß ein Meister oder ein Geselle in Krangheit fiele, oder ein Geselle, der auch in dieser Ordenunge were und der sich uffrechtlich by dem Steinwerk gehalten hett und so lange sich lege, und Ime an seiner Zerunge und notpfrunden abginge; dem sol ein jeder Meister, der dan der Ordenunge Büchse hinder Ime hett, Hülff und bystant tun mit lyhen us der Büchse, vermag ers anders, nutz daß er us den Siechtagen wider uffkemt; so sol er den globen und versprechen, das zu geben und wider in die Büchse zu antwurten. Stürbe aber einer in solichen Sichtagen; so sol man soviel wider nemen von dem, das er noch Tode losset, es sind Kleider oder anders, untz daß das wider vergolten wurt, das Ime dan geliehen ist, ob anders soviel do were.",
         en="2) Alle Meister und Werkleute, die in dieser Ordnung sind und Hütten mit Beschäftigung haben, sollen jeder eine Büchse haben, und jeder Geselle soll jede Woche einen Pfennig in die Büchse geben; und derselbe Meister soll dieses Geld und was sonst anfällt getreulich in der Büchse sammeln und jährlich an die Ordnung abliefern, wo das nächste Buch liegt, um damit den Gottesdienst zu fördern und für die Notdurft unserer Ordnung zu sorgen. [...] 5) Wäre es auch, dass ein Meister oder Geselle in Krankheit fiele, ein Geselle, der auch in dieser Ordnung wäre und sich redlich beim Steinwerk gehalten hätte, und so lange krank läge, dass ihm sein Zehrgeld und Notunterhalt ausginge: dem soll jeder Meister, der die Büchse der Ordnung bei sich hat, Hilfe und Beistand tun mit einem Darlehen aus der Büchse, wenn er es sonst nicht vermag, bis er aus seiner Krankheit wieder aufkommt; dann soll er geloben und versprechen, es zurückzugeben und wieder in die Büchse zu legen. Stürbe aber einer in solcher Krankheit, so soll man so viel von dem zurücknehmen, was er nach seinem Tod hinterlässt, seien es Kleider oder anderes, bis das zurückgezahlt ist, was ihm geliehen wurde, wenn denn so viel da wäre.",
         note="Der Wochenpfennig ist eine Kranken- und Sterbekasse, aber keine Versicherung: Der kranke Geselle bekommt ein Darlehen, kein Geschenk, und stirbt er, nimmt die Büchse seine Kleider. Ausgelassen sind die Artikel über die Ablieferung an die Bücher, die Seelenmesse für Verstorbene und die Kosten der Ordnung (3) und 4))."),
    dict(n=13, titel="Urlaub nur am Samstag", pg="39–40", lang="fnhd",
         orig="Item: wo eine von Muttwillen urlop nympt uff den Haupt Hütten oder uff einer andern Hütten: derselb Geselle sol darnoch in einem Jor uff derselben Hütten umb kein Fürderunge me bitten. Item: wer es auch, daß ein Werkmann oder ein Meister ein wandeln Gesellen in siner Fürderunge hette und wolte dem Urlop geben; dem sol er nit Urlop geben, den uff einen Samstag oder uff einen Lohn obent, uff daß er wisse an dem morgen zu wandeln; er verschuldet es dan mit Ursache. desselben glichen sol auch ein Gesell hinwider tun. Item: Es sol auch kein Geselle niemans anders umb Fürderunge bitten, den den Meister um demselben Werk, oder den Parlierer, weder heimlich noch offentlich on des Meisters Wissen un Willen in der Hütten.",
         en="Item: Wo einer aus Mutwillen auf den Haupthütten oder auf einer anderen Hütte den Abschied nimmt, soll derselbe Geselle danach ein Jahr lang auf derselben Hütte um keine Beschäftigung mehr bitten. Item: Wäre es auch, dass ein Werkmann oder Meister einen wandernden Gesellen in seinem Dienst hätte und ihm den Abschied geben wollte, so soll er ihm den Abschied nur an einem Samstag oder an einem Lohnabend geben, damit er wisse, am Morgen weiterzuwandern; es sei denn, er verschuldet es mit Grund. Ebenso soll es auch ein Geselle umgekehrt halten. Item: Es soll auch kein Geselle jemand anderen um Beschäftigung bitten als den Meister des Werks oder den Parlier, weder heimlich noch öffentlich, ohne Wissen und Willen des Meisters in der Hütte.",
         note="Kündigung nur am Lohntag: Der Geselle soll seinen Lohn haben und am Sonntag wandern können. Die Regel gilt in beide Richtungen. Die Haupthütten sind die mit einem Buch."),
    dict(n=14, titel="Die Diener: ehelich geboren, fünf Jahre", pg="40", lang="fnhd",
         orig="Ordenung der Diener. Zum ersten: Es sol kein Werkmann noch Meister keinen zu Diener uffnemen, der uneelich ist, wissentlich, und sol darumb sin ernstliches erfaren haben, ee er in uffnympt, und einen Solichen Diener by siner Treuwen frogen, ob sin Vatter und mutter In der Ee by einander gesessen sint. Item: Es sol auch kein Werckmann noch Meister keinen seiner Diener, den er von ruhem uff zu diener uffgenommen hett, und der noch in seinen lerjoren ist, zu Parlierer nit machen. Es sol auch kein Werckmann noch Meister keinen, den er von ruhem uff zu Diener uffgenummen hett, und der sin Lerjor ausgedient hett, dennoch zu Parlierer nit machen, er hab den vor ein jor gewandelt. [...] Es sol auch kein Werkmann noch Meister keinen diener von Ruhem uff zu einem diener under Fünff Joren nit uffnemen ungeverlich.",
         en="Ordnung der Diener. Zum Ersten: Kein Werkmann oder Meister soll wissentlich jemanden als Diener aufnehmen, der unehelich ist, und er soll sich darum ernstlich erkundigt haben, ehe er ihn aufnimmt, und einen solchen Diener bei seiner Treue fragen, ob sein Vater und seine Mutter in der Ehe beieinander gesessen sind. Item: Kein Werkmann oder Meister soll einen seiner Diener, den er vom Rauen auf als Diener aufgenommen hat und der noch in seinen Lehrjahren ist, zum Parlier machen. Auch soll kein Werkmann oder Meister einen, den er vom Rauen auf als Diener aufgenommen hat und der seine Lehrjahre ausgedient hat, dennoch zum Parlier machen, er sei denn vorher ein Jahr gewandert. [...] Auch soll kein Werkmann oder Meister einen Diener vom Rauen auf für weniger als fünf Jahre aufnehmen, ohne Arglist.",
         note="Fünf Jahre Lehre ‚vom Rauen auf‘, also vom rohen Stein an, dann ein Jahr Wanderschaft, erst danach Parlier. Ausgeschlossen bleibt, wer unehelich geboren ist; der Meister muss es erfragen. Diese Regel trifft Menschen für etwas, das sie nicht getan haben, und sie gehört zur Geschichte der Zünfte wie ihr Stolz. Ausgelassen ist der Artikel über Diener, die vorher bei einem Maurer gelernt hatten."),
    dict(n=15, titel="Straßburg, Wien, Köln, und Ulm an der Grenze", pg="40–41", lang="fnhd",
         orig="Es ist erkannt uff dem Tage zu Regenßburg vier Wuchen nach Ostern Im Jor do man zält von Gottes Geburt: Tusent vier hundert fünfzig und Nün Jore, uff St. Marrs Tage: daß der Werkmeister Jost Dotzinger von Wurms, des Beues unser lieben Frauwen Münsters der Meren Styfft zu Stroßburg und alle sine Nochkumen, desselben Wercks unser Ordenunge des Steywercks oberster Rychter sin sol. [...] Item: Meister Lorenz Spenning von Wyen sol auch zu Wyen in dem Lande Oeberster Rychter sin. Und also ein Werkmeister nuntzumal oder alle sin nochkumen zu Stroßburg, Wyen und Kölln: die drige sint die Oebersten Rychter und Hauptlütte der Ordenunge; die Sol man nit entsetzen one redelich Ursach. [...] Dis ist das Gebiett, das gon Stroßburg gehört: was obwendig der Musel und Frankenlant untz am Düringer Walt und Babenberg untz an das Bystum gen Eystetten; von Eystetten bis gon Ulm, von Ulm bis gon Augspurg, und von Augspurg byst an den Adelberg und untz an welschlant; Myssener lant und Düringin und Sahssheim lant, Frankfurt und Hessen lant und auch Schwobenlant das sol gehorsam sin.",
         en="Es ist erkannt auf dem Tag zu Regensburg, vier Wochen nach Ostern, im Jahr, da man zählte von Gottes Geburt tausendvierhundertneunundfünfzig Jahre, am Sankt-Markus-Tag: dass der Werkmeister Jost Dotzinger von Worms, des Baues Unserer Lieben Frauen Münster des hohen Stifts zu Straßburg, und alle seine Nachfolger an demselben Werk der oberste Richter unserer Ordnung des Steinwerks sein soll. [...] Item: Meister Lorenz Spenning von Wien soll auch zu Wien im Land oberster Richter sein. Und so sind ein Werkmeister jetzt oder alle seine Nachfolger zu Straßburg, Wien und Köln: Diese drei sind die obersten Richter und Hauptleute der Ordnung; die soll man nicht ohne redlichen Grund absetzen. [...] Dies ist das Gebiet, das nach Straßburg gehört: was oberhalb der Mosel liegt, und Franken bis an den Thüringer Wald und Bamberg, bis an das Bistum Eichstätt; von Eichstätt bis nach Ulm, von Ulm bis nach Augsburg, und von Augsburg bis an den Arlberg und bis an das welsche Land; Meißen, Thüringen und Sachsen, Frankfurt und Hessen und auch Schwaben, das soll gehorsam sein.",
         note="Der Markustag 1459 war der 25. April. Oberster Richter ist der Werkmeister des Straßburger Münsters, einer der Nachfolger Ulrichs von Ensingen auf demselben Posten (Ensingen Straßburg [1]); Ulm gehört zum Straßburger Gebiet. In der Liste der Meister, die in Regensburg auf das Buch gelobten, die Heideloff S. 42 abdruckt, steht kein Meister aus Ulm, wohl aber Meister aus Esslingen, Konstanz, Bern, Passau und Landshut. Was das für Ulm bedeutete, sagt der Text nicht. Mit Heideloffs ‚Adelberg‘ ist wohl der Arlberg gemeint; ausgelassen sind die späteren Bestätigungen zu Speyer 1464 und die Gebiete von Bern und Köln."),
]

doc = {
    "id": "huette",
    "titel": "Die Ordnung der Steinmetzen, Regensburg 1459",
    "autor": "Die Meister und Gesellen des Steinwerks (Tag zu Regensburg)",
    "jahr": "1459",
    "sprache": "de",
    "orig_sprache": "fnhd",
    "pg_label": "Heideloff S.",
    "quelle": "Carl Alexander Heideloff, Die Bauhütte des Mittelalters in Deutschland (Nürnberg 1844), Beilage Nro. 1 „Ordenunge der Steinmetzen zu Strasburg 1459“, S. 34–42 (Internet Archive: 10048396bsb, Digitalisat der Bayerischen Staatsbibliothek). Übersetzung: eigene Arbeitsübersetzung.",
    "hinweis": "Die Ordnung, die sich die Meister und Gesellen der Bauhütten am 25. April 1459 in Regensburg gaben, nach der Straßburger Fassung, die Heideloff 1844 abdruckt; ausgewählte Artikel, in Fraktur am Seitenbild gelesen. Heideloffs erklärende Zusätze in Klammern sind weggelassen, Auslassungen mit [...] bezeichnet. Heideloffs Text ist keine kritische Edition; für eine wissenschaftliche Arbeit ist die neuere Edition der Steinmetzordnungen heranzuziehen. Die Übersetzung ist eigene Arbeit (CC0).",
    "sections": [
        {"id": "ordnung", "titel": "Die Ordnung", "zk": "Hütte",
         "blurb": "Wie die Bauhütten sich selbst regierten: Taglohn statt Akkord, Nachfolge beim Tod des Meisters, Bindung an die Visierung, Boykott gegen den, der einem Meister das Werk abjagt, kein Wissen um Geld, höchstens fünf Lehrlinge, Sittenregeln, eine Büchse für Kranke, fünf Jahre Lehre, und Straßburg als oberster Richter über ein Gebiet bis Ulm.",
         "units": ORDNUNG},
    ],
}

OUT.write_text(json.dumps(doc, ensure_ascii=False, indent=1), encoding="utf-8")
print("huette.json:", sum(len(s["units"]) for s in doc["sections"]), "Einheiten")
