"""Baut data/vergleich.json: Straßburg und Köln, die beiden anderen großen Türme, in zwei Stimmen:
Goethes ‚Von deutscher Baukunst‘ (1772/73) über das Straßburger Münster und Sulpiz Boisserées
‚Geschichte und Beschreibung des Doms von Köln‘ (1842).

Goethe: Von deutscher Baukunst. D. M. Ervini a Steinbach, Erstdruck 1772; hier nach dem Druck in
Herders ‚Von deutscher Art und Kunst‘ (Hamburg 1773), im Neudruck von Hans Lambel (Stuttgart:
Göschen 1892), S. 83, 86–89. Internet Archive vondeutscherartu00frisuoft; S. 83 = Blatt 144, S. 87 =
Blatt 148, fortlaufend. In Fraktur; am Seitenbild gelesen. Schreibung und Zeichensetzung des Drucks
von 1773 sind beibehalten. Übertragung ins heutige Deutsch: eigene Arbeit (CC0).

Boisserée: Geschichte und Beschreibung des Doms von Köln (2. Ausgabe, München 1842), S. 86 und
106–107. Internet Archive 10048242bsb (Digitalisat der Bayerischen Staatsbibliothek); S. 86 =
Blatt 101, S. 106 = Blatt 121. In Fraktur; am Seitenbild gelesen. Ohne Übersetzung.
"""
import json
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "data" / "vergleich.json"

GOETHE = [
    dict(n=1, titel="Der Grabstein, den keiner zeigen konnte", pg="83", lang="de",
         orig="Als ich auf deinem Grabe herumwandelte, edler Erwin, und den Stein suchte, der mir deuten sollte: Anno domini 1318. XVI. Kal. Febr. obiit Magister Ervinus, Gubernator Fabricæ Ecclesiæ Argentinensis, und ich ihn nicht finden, keiner deiner Landsleute, mir ihn zeigen konnte, daß sich meine Verehrung deiner, an der heiligen Stätte ergossen hätte; da ward ich tief in die Seele betrübt, und mein Herz, jünger, wärmer, thöriger und besser als jetzt, gelobte dir ein Denkmal [...].",
         en="Als ich auf deinem Grab umherwanderte, edler Erwin, und den Stein suchte, der mir anzeigen sollte: ‚Im Jahr des Herrn 1318, am 17. Januar, starb Meister Erwin, Leiter des Baus der Straßburger Kirche‘, und ich ihn nicht finden konnte und keiner deiner Landsleute ihn mir zeigen konnte, damit sich meine Verehrung für dich an der heiligen Stätte hätte ergießen können, da wurde ich tief in der Seele betrübt, und mein Herz, jünger, wärmer, törichter und besser als jetzt, gelobte dir ein Denkmal [...].",
         note="Goethe studierte 1770/71 in Straßburg; der Aufsatz erschien 1772 als anonymes Heft und 1773 in Herders Sammlung ‚Von deutscher Art und Kunst‘. ‚Gubernator Fabricæ‘ ist dasselbe Amt, das in Ulm ‚Meister, Ausrichter und Verweser‘ heißt (Ensingen Ulm [1]). Achtzig Jahre nach Erwin wurde Ulrich von Ensingen Werkmeister an diesem Münster (Ensingen Straßburg [1]) und baute das Achteck des Turms, an dem er sein Zeichen setzte (Tafel ‚Ulrichs Zeichen‘). Goethe sucht den Meister und findet nicht einmal seinen Grabstein; die Meister der Bauhütten waren vergessen, bis die Romantik sie suchte."),
    dict(n=2, titel="Ein Baum Gottes", pg="86", lang="de",
         orig="Eure Gebäude stellen euch also Flächen dar, die, je weiter sie sich ausbreiten, je kühner sie gen Himmel steigen, mit desto unerträglicherer Einförmigkeit die Seele unterdrücken müssen! Wohl! wenn uns der Genius nicht zu Hülfe käme, der Erwinen von Steinbach eingab: vermannigfaltige die ungeheure Mauer, die du gen Himmel führen sollst, daß sie aufsteige gleich einem hocherhabnen, weit verbreiteten Baume Gottes, der mit tausend Aesten, Millionen Zweigen, und Blättern wie der Sand am Meer, rings um, der Gegend verkündet, die Herrlichkeit des Herrn, seines Meisters.",
         en="Eure Gebäude stellen euch also Flächen dar, die, je weiter sie sich ausbreiten, je kühner sie zum Himmel steigen, die Seele mit desto unerträglicherer Einförmigkeit bedrücken müssen! Wohl uns, wenn uns der Genius nicht zu Hilfe käme, der Erwin von Steinbach eingab: Vermannigfaltige die ungeheure Mauer, die du zum Himmel führen sollst, dass sie aufsteige gleich einem hoch erhabenen, weit ausgebreiteten Baum Gottes, der mit tausend Ästen, Millionen Zweigen und Blättern wie Sand am Meer ringsum der Gegend die Herrlichkeit des Herrn, seines Meisters, verkündet.",
         note="‚Eure Gebäude‘: Goethe redet gegen die Architekturtheoretiker seiner Zeit, die nach antikem Vorbild die Säule zum Wesen der Baukunst erklärten, namentlich den ‚lieben Abt‘ Laugier, den er im Absatz davor anspricht. Das Bild vom Baum Gottes ist das Gegenteil dessen, was die Bauhütten selbst über ihre Kunst sagten: Für sie war sie eine Sache von Maß und Geometrie, die man ‚aus dem Grund nehmen‘ musste (Hütte [7], Tafel ‚Aus dem Grund genommen‘). Goethe sieht Natur, wo die Meister rechneten."),
    dict(n=3, titel="Gotisch, ein Schimpfwort", pg="87", lang="de",
         orig="Als ich das erstemal nach dem Münster gieng, hatte ich den Kopf voll allgemeiner Erkenntniß guten Geschmacks. Auf Hörensagen ehrt ich die Harmonie der Massen, die Reinheit der Formen, war ein abgesagter Feind der verworrnen Willkührlichkeiten gothischer Verzierungen. Unter die Rubrik Gothisch, gleich dem Artikel eines Wörterbuchs, häufte ich alle synonimische Mißverständnisse, die mir von unbestimmtem, ungeordnetem, unnatürlichem, zusammengestoppeltem, aufgeflicktem, überladenem, jemals durch den Kopf gezogen waren. Nicht gescheider als ein Volk, das die ganze fremde Welt barbarisch nennt, hieß alles gothisch, was nicht in mein System paßte, von dem gedrechselten, bunten Puppen- und Bilderwerk an, womit unsre bürgerliche Edelleute ihre Häuser schmücken, bis zu den ernsten Resten der älteren deutschen Baukunst, über die ich, auf Anlaß einiger abentheuerlichen Schnörkel, in den allgemeinen Gesang stimmte: „Ganz von Zierrath erdrückt!„ und so graute mirs im Gehen vorm Anblick eines mißgeformten krausborstigen Ungeheuers. Mit welcher unerwarteten Empfindung überraschte mich der Anblick, als ich davor trat. Ein, ganzer, grosser Eindruck füllte meine Seele, den, weil er aus tausend harmonirenden Einzelnheiten bestand, ich wohl schmecken und geniessen, keineswegs aber erkennen und erklären konnte.",
         en="Als ich das erste Mal zum Münster ging, hatte ich den Kopf voll allgemeiner Kenntnis des guten Geschmacks. Vom Hörensagen ehrte ich die Harmonie der Massen und die Reinheit der Formen und war ein erklärter Feind der verworrenen Willkürlichkeiten gotischer Verzierungen. Unter dem Stichwort ‚gotisch‘ häufte ich, wie im Artikel eines Wörterbuchs, alle gleichbedeutenden Missverständnisse an, die mir je von Unbestimmtem, Ungeordnetem, Unnatürlichem, Zusammengestoppeltem, Aufgeflicktem, Überladenem durch den Kopf gegangen waren. Nicht klüger als ein Volk, das die ganze fremde Welt barbarisch nennt, hieß alles gotisch, was nicht in mein System passte, vom gedrechselten, bunten Puppen- und Bilderwerk an, mit dem unsere bürgerlichen Edelleute ihre Häuser schmücken, bis zu den ernsten Resten der älteren deutschen Baukunst, über die ich wegen einiger abenteuerlicher Schnörkel in den allgemeinen Gesang einstimmte: ‚Ganz von Zierrat erdrückt!‘ Und so graute mir im Gehen vor dem Anblick eines missgestalteten, kraushaarigen Ungeheuers. Mit welcher unerwarteten Empfindung überraschte mich der Anblick, als ich davortrat! Ein ganzer, großer Eindruck füllte meine Seele, den ich, weil er aus tausend harmonierenden Einzelheiten bestand, wohl schmecken und genießen, keineswegs aber erkennen und erklären konnte.",
         note="‚Gotisch‘ war im 18. Jahrhundert ein Schimpfwort für das Barbarische, Ungeordnete; Goethe beschreibt, wie er es selbst so gebrauchte. Goethes Bekehrung vor dem Münster ist der Anfang einer Umwertung: Ein halbes Jahrhundert später heißt Falgers Tafelwerk, in dem das Ulmer Münster steht, ‚Abbildung der vornehmsten Gebäude altdeutscher Bauart‘ (Tafel ‚Der Stumpf, 1829‘), ‚altdeutsch‘ statt ‚gotisch‘. Aus dieser Begeisterung wurde 1844 in Ulm wieder gebaut (Gartenlaube [3])."),
    dict(n=4, titel="Nur einer der Türme", pg="88", lang="de",
         orig="Da offenbarte sich mir, in leisen Ahndungen, der Genius des grossen Werkmeisters. Was staunst du, lispelt er mir entgegen. Alle diese Massen waren nothwendig, und siehst du sie nicht an allen älteren Kirchen meiner Stadt. Nur ihre willkührlichen Grössen hab ich zum stimmenden Verhältniß erhoben. Wie über dem Haupteingang, der zwey kleinere zu’n Seiten beherrscht, sich der weite Kreis des Fensters öffnet, der dem Schiffe der Kirche antwortet, und sonst nur Tageloch war, wie, hoch drüber der Glockenplatz die kleineren Fenster forderte! das all war nothwendig, und ich bildete es schön. Aber ach, wenn ich durch die düstern erhabnen Oeffnungen hier zur Seite schwebe, die leer und vergebens da zu stehn scheinen. In ihre kühne schlanke Gestalt hab ich die geheimnißvollen Kräfte verborgen, die jene beyden Thürme hoch in die Luft heben sollten, deren, ach, nur einer traurig da steht, ohne den fünfgethürmten Hauptschmuck, den ich ihm bestimmte, daß ihm und seinem königlichen Bruder die Provinzen umher huldigten. Und so schied er von mir, und ich versank in theilnehmende Traurigkeit.",
         en="Da offenbarte sich mir in leisen Ahnungen der Genius des großen Werkmeisters. ‚Was staunst du?‘, flüsterte er mir zu. ‚Alle diese Massen waren notwendig; siehst du sie nicht an allen älteren Kirchen meiner Stadt? Nur ihre willkürlichen Größen habe ich zum stimmigen Verhältnis erhoben. Wie sich über dem Haupteingang, der zwei kleinere zu seinen Seiten beherrscht, der weite Kreis des Fensters öffnet, der dem Kirchenschiff antwortet und sonst nur ein Lichtloch war; wie hoch darüber der Glockenstuhl die kleineren Fenster verlangte! Das alles war notwendig, und ich gestaltete es schön. Aber ach, wenn ich durch die düsteren, erhabenen Öffnungen hier zur Seite schwebe, die leer und vergeblich dazustehen scheinen! In ihre kühne, schlanke Gestalt habe ich die geheimnisvollen Kräfte verborgen, die jene beiden Türme hoch in die Luft heben sollten, von denen, ach, nur einer traurig dasteht, ohne den fünftürmigen Hauptschmuck, den ich ihm bestimmte, damit ihm und seinem königlichen Bruder die Provinzen ringsum huldigten.‘ Und so schied er von mir, und ich versank in teilnehmende Traurigkeit.",
         note="Der Geist des Meisters klagt über den unvollendeten Bau: Von zwei Türmen steht nur einer, und auch ihm fehlt der geplante Schmuck. Es ist dieselbe Klage, die Fabri 1488 über Ulm führte (Fünf Werke [2]): Der Plan der Gründer war größer als das, was die Späteren bauten. Goethe weiß nicht, dass der eine Straßburger Turm, den er sieht, im Achteck auf Ulrich von Ensingen zurückgeht, den Meister des Ulmer Turms; der Helm darüber wurde 1439 vollendet. Ulm hatte 1773 nur einen Stumpf (Tafel ‚Der Stumpf, 1829‘)."),
    dict(n=5, titel="Deutsche Baukunst, unsre Baukunst", pg="88–89", lang="de",
         orig="Und nun soll ich nicht ergrimmen, heiliger Erwin, wenn der deutsche Kunstgelehrte, auf Hörensagen neidischer Nachbarn, seinen Vorzug verkennt, dein Werk mit dem unverstandnen Worte gothisch verkleinert. Da er Gott danken sollte, laut verkündigen zu können, das ist deutsche Baukunst, unsre Baukunst, da der Italiäner sich keiner eignen rühmen darf, vielweniger der Franzos. Und wenn du dir selbst diesen Vorzug nicht zugestehen willst, so erweis uns, daß die Gothen schon wirklich so gebaut haben, wo sich einige Schwürigkeiten finden werden. [...] Hüte dich, den Namen deines edelsten Künstlers zu entheiligen, und eile herbey, daß du schauest sein trefliches Werk. Macht es dir einen widrigen Eindruck, oder keinen, so gehab dich wohl, laß einspannen, und so weiter nach Paris.",
         en="Und nun soll ich nicht ergrimmen, heiliger Erwin, wenn der deutsche Kunstgelehrte auf das Hörensagen neidischer Nachbarn hin seinen Vorzug verkennt und dein Werk mit dem unverstandenen Wort ‚gotisch‘ verkleinert? Da er doch Gott danken sollte, laut verkünden zu können: Das ist deutsche Baukunst, unsere Baukunst, während der Italiener sich keiner eigenen rühmen darf, und noch viel weniger der Franzose. Und wenn du dir selbst diesen Vorzug nicht zugestehen willst, so beweise uns, dass die Goten schon wirklich so gebaut haben, wobei sich einige Schwierigkeiten finden werden. [...] Hüte dich, den Namen deines edelsten Künstlers zu entheiligen, und eile herbei, dass du sein treffliches Werk schaust. Macht es dir einen widrigen Eindruck oder gar keinen, so leb wohl, lass einspannen, und weiter nach Paris.",
         note="Der folgenreichste Irrtum des Aufsatzes: Die gotische Baukunst ist in Frankreich entstanden, in der Île-de-France um 1140, und nicht in Deutschland; der Franzose, den Goethe hier verspottet, hätte sich ihrer sehr wohl rühmen dürfen. Goethe sah das später selbst nüchterner. Aber das Wort ‚deutsche Baukunst, unsre Baukunst‘ blieb und trug die Vollendung der Dome in Köln und Ulm: 1890 feierte Pfleiderer den Ulmer Turm als Werk ‚deutscher Kraft und deutschen Geistes‘ (Gartenlaube [1]). ‚Lass einspannen, und weiter nach Paris‘: Goethe setzt deutsch gegen französisch, an einem Bau, dessen Stadt seit 1681 zu Frankreich gehörte."),
]

BOISSEREE = [
    dict(n=1, titel="Ulm, wo man am Strebewerk sparte", pg="86",
         en="Gegen diesen Zweifel ist einzuwenden, daß Widerhalter und Strebebogen allgemein an den größeren Gewölbhallen altdeutscher Baukunst vorkommen, selbst wenn sie bei weitem nicht so hoch emporragen als am kölner Dom und daß dort, wo sie fehlen, meistens die Anlage dazu sich entdecken, die Ursache weshalb die Ausführung unterblieben, sich nachweisen läßt. So sehen wir, um nur wenige Beispiele zu erwähnen, an der großen Kirche zu Ulm und an der kleinen Stiftskirche zu Wimpfen im Thal die Anlagen zu Strebebogen; und bei beiden Gebäuden begreifen wir, wie man sich die Ersparniß hat erlauben dürfen, das Strebewerk wegzulassen. Bei der Kirche zu Wimpfen gestatteten es die sehr mäßigen Verhältnisse und bei der ulmer Kirche verschiedene Umstände, einmal weil die Haupthalle dort, obwohl sie sehr hoch ist, doch nicht sehr über den Nebenhallen emporragt, dann weil sie nur kleine Fenster hat, so daß neben denselben noch ein breites Mauerwerk zur Verstärkung der Pfeiler eintritt. Jedoch sind an beiden Gebäuden, besonders an der Kirche zu Wimpfen, die nachtheiligen Folgen der Weglassung des Strebewerks bemerkbar.",
         note="Boisserée, der Kölner Sammler und Betreiber der Kölner Domvollendung, nennt Ulm als Beispiel einer Kirche, an der man ‚sich die Ersparniß‘ der Strebebögen erlaubte, obwohl ihre Anlage vorbereitet war. Es ist der Gegensatz, den Fabri mit den ‚parvifici‘ meinte (Fünf Werke [2]): Der Plan sah mehr vor, als gebaut wurde. Vierzehn Jahre nach Boisserées Buch, ab 1856, setzte Thrän in Ulm die fehlenden Strebebögen, ‚die mächtigsten, welche ein deutscher Dom aufweist‘ (Gartenlaube [3])."),
    dict(n=2, titel="Der Riss auf dem Speicher", pg="106–107",
         en="Der Aufriß des nördlichen Thurmes, auf das sorgfältigste gezeichnet, wurde ehemals im Archiv des kölnischen Domstiftes aufbewahrt. Als dies Archiv in Folge des Lüneviller Friedens von den Abgeordneten der verschiedenen Fürsten, denen die kölnischen Lande anheim gefallen waren, in Darmstadt getheilt wurde, ging der Riß durch die größte Gleichgültigkeit und Nachläßigkeit verloren; alle meine wiederholten Bemühungen, ihn aufzufinden, alle Nachfragen bei den mit der Theilung beauftragt gewesenen Personen waren vergebens, niemand erinnerte sich die große Pergamentrolle gesehen zu haben. Es gehörte, bedeutsam genug, nichts weniger als die Befreiung Deutschlands und ein dadurch veranlaßter Zufall dazu, um diese unschätzbare Bauurkunde wieder an den Tag zu fördern. Denn sie war auf einen Speicher gerathen, wo im Jahr 1814 ein Triumphbogen für die heimkehrenden Freiwilligen gemalt werden sollte, und hier entdeckte sie ein Dekorationsmaler und rettete sie vom Verderben. Der Speicher gehörte zu einem Gasthof, dem nämlichen Hause, in welchem das Archiv war getheilt worden. Man hatte sich des auf Pergament gezeichneten Risses bedient, um Bohnen darauf zu trocknen, und hatte ihn zu diesem Ende aufgenagelt. Zum Glück aber fand sich außer einigen Flecken und Nagellöchern nur eine einzige Stelle bedeutend verletzt, indem an der Seite des mittlern Giebels und Fensters ein langer Streifen herausgerissen war. Der glückliche Finder überließ den Plan dem Oberbaurath Moller in Darmstadt, welcher an meinen Arbeiten durch Verfertigung einer trefflichen Zeichnung theilgenommen hatte; und dieser gab im Jahr 1818 in sieben großen Blättern ein Facsimile der ehrwürdigen Bau-Urkunde heraus.",
         note="Die Geschichte des Kölner Fassadenrisses, Bohnen und Nagellöcher inbegriffen, wird bei Boisserée zur nationalen Legende: ‚die Befreiung Deutschlands‘ von 1814 bringt den Plan zurück. In Ulm lag der Riss Böblingers ruhiger in einer Kapelle des Münsters (Gartenlaube [2]); die Ratsverträge hatten verlangt, dass Meister beim Abgang ihre Visierungen zurückgaben (Pfleiderer [1]). In beiden Städten machte erst der wiedergefundene oder wiedergelesene mittelalterliche Plan die Vollendung im 19. Jahrhundert möglich, und in beiden wurde sie als nationale Tat gefeiert."),
]

doc = {
    "id": "vergleich",
    "titel": "Straßburg und Köln",
    "autor": "Johann Wolfgang Goethe (1772/73); Sulpiz Boisserée (1842)",
    "jahr": "1772–1842",
    "sprache": "de",
    "orig_sprache": "de",
    "pg_label": "S.",
    "quelle": "J. W. Goethe, Von deutscher Baukunst (1772), nach dem Druck in: Von deutscher Art und Kunst (Hamburg 1773), Neudruck hg. von H. Lambel (Stuttgart 1892), S. 83, 86–89 (Internet Archive: vondeutscherartu00frisuoft); S. Boisserée, Geschichte und Beschreibung des Doms von Köln (München 1842), S. 86, 106–107 (Internet Archive: 10048242bsb). Übertragung Goethes: eigene Arbeit.",
    "hinweis": "Was andere Städte mit ihren Türmen taten, und wie man im 18. und 19. Jahrhundert über sie sprach: Goethes Hymnus auf das Straßburger Münster, das wie Ulm nur einen Turm hatte und dessen Achteck Ulrich von Ensingen baute, und Boisserées Geschichte des Kölner Doms, die Ulm als Beispiel des Sparens am Strebewerk nennt und erzählt, wie der verlorene Kölner Riss 1814 wiedergefunden wurde. Beide Texte in Fraktur am Seitenbild gelesen; Goethes mit einer Übertragung ins heutige Deutsch, Boisserées ohne. Die Anmerkungen nennen Goethes Irrtum, die Gotik sei deutsch. Die Übertragung ist eigene Arbeit (CC0).",
    "sections": [
        {"id": "goethe", "titel": "Goethe 1772: Von deutscher Baukunst", "zk": "Goethe",
         "blurb": "Der junge Goethe vor dem Straßburger Münster: der Grabstein Erwins, den keiner zeigen konnte, der Baum Gottes, ‚gotisch‘ als Schimpfwort, der Geist des Meisters, der klagt, dass nur einer der beiden Türme steht, und der folgenreiche Irrtum: ‚das ist deutsche Baukunst, unsre Baukunst‘.",
         "units": GOETHE},
        {"id": "boisseree", "titel": "Boisserée 1842: Der Dom von Köln", "zk": "Boisserée",
         "blurb": "Der Kölner Sammler und Betreiber der Domvollendung: Ulm als Beispiel einer Kirche, an der man am Strebewerk sparte, und die Geschichte des Kölner Fassadenrisses, auf dem man Bohnen trocknete, bis ihn die ‚Befreiung Deutschlands‘ 1814 wieder ans Licht brachte.",
         "units": BOISSEREE},
    ],
}

OUT.write_text(json.dumps(doc, ensure_ascii=False, indent=1), encoding="utf-8")
print("vergleich.json:", sum(len(s["units"]) for s in doc["sections"]), "Einheiten")
