"""Baut data/buergerkirche.json: Felix Fabri darüber, wie Ulm die Rechte an seiner Pfarrkirche
den Klöstern Reichenau und Bebenhausen abkaufte, und über die Pfleger, die der Rat über das
Geld der Kirche, des Spitals und der Armen setzte.

Latein: Fratris Felicis Fabri Tractatus de civitate Ulmensi, hg. von Gustav Veesenmeyer
(Bibliothek des Litterarischen Vereins in Stuttgart 186, Tübingen 1889), S. 24–27 und 131–132.
Internet Archive fratrisfelicisf03fabrgoog; im PDF dieser Aufnahme ist PDF-Seite = Druckseite + 20
für S. 24–27, aber Druckseite + 16 für S. 131–132 (gezählt ab 0). Am Seitenbild gelesen; die
maschinelle Texterkennung diente nur der Orientierung. Veesenmeyers Schreibung (æ, œ) ist
beibehalten, seine Fußnotenzeichen sind weggelassen. Übersetzung: eigene Arbeitsübersetzung (CC0).
"""
import json
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "data" / "buergerkirche.json"

REICHENAU = [
    dict(n=1, titel="Unter dem Joch der Mönche", pg="24–25", lang="la",
         orig="Sic ergo Ulmenses longo tempore sub iugo monachorum et regimine eorum degebant, eosque tanquam dominos suos recognoscebant, et ministri eorum voluntarii erant, quamdiu monachi ministri Dei devoti manserunt. Tandem autem religione tepescente et seculari pompa in monachis crescente, Deo permittente tepuit in Ulmensibus amor et affectus ac obedientia ad monachos illos, videbant enim quod de bonis eorum nutriebatur superbia cum multorum scandalo. Unde abbates illi illo tempore magnis sumptibus a sede apostolica impetraverunt pontificalia insignia supra suas dignitates, contra quod tamen sanctus Bernhardus, qui illis temporibus adhuc in humanis erat, multa scripsit [...]. Sic ergo, ad propositum, in dies expensis crescentibus crescebant necessario exactiones subditorum et gravamina indebita, unde Ulmenses onerati gemere cœperunt et de excutiendo iugo illo inter se tractaverunt, quia tamen prudentes erant, non subito sed paulatim libertatem quæsierunt cum amicitia suorum dominorum.",
         en="So lebten die Ulmer lange Zeit unter dem Joch der Mönche und ihrer Herrschaft, erkannten sie als ihre Herren an und dienten ihnen willig, solange die Mönche fromme Diener Gottes blieben. Als aber endlich die Frömmigkeit erkaltete und der weltliche Prunk unter den Mönchen wuchs, erkaltete, wie Gott es zuließ, bei den Ulmern die Liebe, die Zuneigung und der Gehorsam gegenüber jenen Mönchen; denn sie sahen, dass von deren Gütern der Hochmut genährt wurde, zum Ärgernis vieler. Darum erwirkten jene Äbte damals mit großen Kosten vom Apostolischen Stuhl bischöfliche Abzeichen über ihre Würde hinaus, wogegen doch der heilige Bernhard, der zu jener Zeit noch unter den Lebenden war, vieles schrieb [...]. So also, um zur Sache zu kommen, wuchsen mit den täglich wachsenden Ausgaben notwendig die Abgaben der Untertanen und die ungeschuldeten Lasten; darum begannen die Ulmer unter der Last zu seufzen und berieten untereinander, wie sie jenes Joch abschütteln könnten. Weil sie aber klug waren, suchten sie die Freiheit nicht plötzlich, sondern allmählich, und in Freundschaft mit ihren Herren.",
         note="Die Mönche sind die der Benediktinerabtei Reichenau im Bodensee (‚Owia‘, ‚Augia‘), der nach der Klosterüberlieferung Karl der Große Ulm geschenkt hatte, und die der Zisterze Bebenhausen bei Tübingen, die in der Stadt die Kirche des heiligen Georg besaß (S. 24). Reichenau war Patron der Ulmer Pfarrkirche, und seit 1327 war ihm die Pfarrei nach der neueren Landesbeschreibung (LEO-BW) inkorporiert. Ausgelassen ist Fabris Abschweifung mit Bernhard von Clairvaux, einer Dekretale gegen die ‚gehörnten Esel‘ mit Mitra und einem derben Sprichwort über Prälaten, die bischöfliche Abzeichen tragen und doch nichts hervorbringen. Fabri war selbst Mönch, Dominikaner; sein Spott gilt den reichen alten Orden."),
    dict(n=2, titel="Die Klöster verkaufen", pg="25–26", lang="la",
         orig="Porro ambo illa monasteria Bebahusen et Owia in dies decrescebant in temporalibus, quia spiritualia iam diu desierant florere, unde coacti abbates iura sua Ulmensibus paulatim vendere cœperunt. Emerunt autem Ulmenses primo omnia iura abbatis de Bebahusen et habitationes eorum et cellare, et ea in usum reipublicæ converterunt, omnia destruentes præter ecclesiam, quæ adhuc hodie domino de Wirtenberg attinet, qui ius patronatus a monachis prædictis emit. In illo autem contractu Ulmensium cum monachis duo intendebant efficere Ulmenses, primum quod eorum iura et bona in civitatis venirent usum et potestatem: secundum quod ipsos monachos excluderent a civitate, et utrumque factum est.",
         en="Beide Klöster aber, Bebenhausen und die Reichenau, nahmen im Zeitlichen von Tag zu Tag ab, weil das Geistliche schon lange nicht mehr blühte; darum begannen die Äbte gezwungenermaßen, ihre Rechte nach und nach an die Ulmer zu verkaufen. Die Ulmer kauften zuerst alle Rechte des Abtes von Bebenhausen und die Wohnungen der Mönche und den Keller und verwandten sie zum Nutzen des Gemeinwesens; sie rissen alles ab außer der Kirche, die noch heute dem Herrn von Württemberg gehört, der das Patronatsrecht von den genannten Mönchen kaufte. Bei diesem Handel der Ulmer mit den Mönchen wollten die Ulmer zweierlei erreichen: erstens, dass deren Rechte und Güter in den Gebrauch und die Gewalt der Stadt kämen; zweitens, dass sie die Mönche selbst aus der Stadt ausschlössen. Und beides geschah.",
         note="Die Kirche, die Württemberg behielt, ist die Georgskirche der Bebenhausener; ihretwegen musste die Stadt 1377 den Grafen von Württemberg um Zustimmung zum Bauplatz bitten (Grundstein [3]). Fabri gibt die Absicht der Stadt offen an: Es ging nicht nur um Rechte und Güter, sondern darum, die Mönche aus der Stadt zu bekommen. Veesenmeyer verzeichnet, dass mehrere Handschriften die beiden Ziele in umgekehrter Reihenfolge nennen, den Ausschluss der Mönche zuerst."),
    dict(n=3, titel="Der Abt in Ulm", pg="26", lang="la",
         orig="Unde abbas Owiæ frequenter erat in Ulma, et quasi curiam non principis sed regis ibi habebat, cui Ulmenses pecunias ad desiderium commodabant, quibus decimas, census, telonea et iura impignorabat, multa etiam ad vitam quorundam tribuebat, alia sponte propinabat, nec erat dies in quo non alienaretur aliquid ab eo consentiente eo. Aliquando, ut audivi, ante carnisprivium quasi omnes de Owia Ulmæ erant et cum civibus hastiludiis, choreis, nuptiis, conviviis et omnibus voluptatibus deserviebant, et tantas expensas faciebant, quod non erat dies in quo non aliqua villa vel decima in cassum transibat. Et cum hoc in tanta debita deductus fuit in Ulma abbas, quod non fuit quæstio iam de rebus abbatis in Ulma, sed quærebantur iam res extra etiam procul ab Ulma. In his sculteto et consulatui multa dedit et indulsit, et coactus iura sua continue resignavit, sed et curiam suam den Grienenhof civibus vendidit, qui ex horto plateam publicam fecerunt, in qua olera et fructus vendebantur, et de horreo, quod iam est domus Wilhelmi Lew, zecham vel tabernam civium fecerunt. Mansit autem platea illa forum venalium rerum usque ad civitatis ampliationem.",
         en="Darum war der Abt der Reichenau häufig in Ulm und hielt dort gleichsam einen Hof, nicht wie ein Fürst, sondern wie ein König; die Ulmer liehen ihm Geld, so viel er wollte, und er verpfändete ihnen dafür Zehnten, Zinsen, Zölle und Rechte; vieles gab er auch einigen auf Lebenszeit, anderes verschenkte er freiwillig, und es verging kein Tag, an dem ihm nicht mit seiner Zustimmung etwas entfremdet wurde. Bisweilen, wie ich gehört habe, waren vor der Fastnacht fast alle von der Reichenau in Ulm und gaben sich mit den Bürgern Turnieren, Tänzen, Hochzeiten, Gelagen und allen Vergnügungen hin und machten so große Ausgaben, dass kein Tag verging, an dem nicht ein Dorf oder ein Zehnt verloren ging. Und damit geriet der Abt in Ulm in so große Schulden, dass es nicht mehr um die Sachen des Abtes in Ulm ging, sondern man schon nach Sachen außerhalb, auch weit weg von Ulm, griff. Dabei gab und gewährte er dem Schultheißen und dem Rat vieles, gab gezwungen seine Rechte fortwährend auf, und verkaufte den Bürgern sogar seinen Hof, den Grünen Hof; die machten aus dem Garten einen öffentlichen Platz, auf dem Gemüse und Obst verkauft wurden, und aus der Scheuer, die jetzt das Haus des Wilhelm Lew ist, eine Trinkstube oder Schenke der Bürger. Dieser Platz blieb ein Markt für Waren bis zur Erweiterung der Stadt.",
         note="Fabri beschreibt keinen Raub, sondern ein Geschäft mit beiderseitigem Vergnügen: Die Ulmer leihen, der Abt verpfändet, die Pfänder verfallen. ‚Ut audivi‘, wie ich gehört habe: Für die Feste vor der Fastnacht beruft sich Fabri auf Hörensagen. Der Grüne Hof, nach S. 24 einst Garten und Baumgarten der Mönche, ist bis heute ein Platz in Ulm."),
    dict(n=4, titel="Was die Ulmer gegen das Recht taten", pg="26–27", lang="la",
         orig="Hæc autem omnia non unus abbas, sed plures successive agebant, et ad tantam perversitatem res devenit, ut abbate aliquo defuncto Ulmenses promoverent quem vellent, qui nullum utilem monasterio, sed suæ civitati benevolum eligi permiserunt. In tanto autem contemptu et despectu haberi cœperunt abbates ab Ulmensibus, ut mortuo aliquo plebano ipsi eligerent et pro eius confirmatione et investitura ad sedem apostolicam mitterent, et non ad abbatem ad quem de iure spectabat. Nam in omnibus his Ulmenses multa de facto fecerunt, quæ sacris canonibus et legibus contraria erant, et monachi ius pro se habebant, sed negligentes, formidulosi et dormientes erant. Vigilantibus autem et non dormientibus iura subveniunt [...].",
         en="Das alles aber tat nicht ein Abt, sondern mehrere nacheinander, und die Sache kam so weit in Verkehrtheit, dass die Ulmer, wenn ein Abt gestorben war, durchsetzten, wen sie wollten, und keinen wählen ließen, der dem Kloster nützlich, sondern nur einen, der ihrer Stadt wohlgesinnt war. Die Äbte aber fingen an, bei den Ulmern in solcher Verachtung und Geringschätzung zu stehen, dass die Ulmer, wenn ein Pfarrer gestorben war, selbst einen wählten und zu seiner Bestätigung und Einsetzung an den Apostolischen Stuhl schickten, und nicht an den Abt, dem es von Rechts wegen zustand. Denn in all dem taten die Ulmer vieles mit der Tat, was den heiligen Kanones und den Gesetzen zuwiderlief, und die Mönche hatten das Recht auf ihrer Seite; aber sie waren nachlässig, furchtsam und schläfrig. Den Wachen aber, nicht den Schlafenden, kommen die Rechte zu Hilfe [...].",
         note="Fabri, sonst der Lobredner seiner Stadt, sagt hier deutlich, dass die Ulmer gegen das Kirchenrecht handelten: Sie bestimmten die Wahl der Äbte und setzten Pfarrer an den Patronen vorbei ein. Er entschuldigt es mit dem Rechtssatz, dass das Recht den Wachsamen hilft, und belegt ihn mit Stellen aus den Institutionen und den Digesten (hier ausgelassen). ‚De facto‘ steht gegen ‚de iure‘: was man tut, gegen was einem zusteht."),
    dict(n=5, titel="Vierzehn Jahre im Bann, 24 000 Gulden", pg="27", lang="la",
         orig="Multis autem bonis perditis et iuribus amissis aperti sunt monachorum oculi et cœperunt cum Ulmensibus contendere et in litem trahere et novas expensas inutiles facere; sicque multis annis in diversitate steterunt. Unde per quatuordecim annos Ulmenses in excommunicatione erant apostolica propter monachos, nec tamen ad monachos illos inclinari poterant, sed instanter apud papam et imperatorem laborabant ut liberarentur ab eis, quod tamen videbatur nullo iure posse fieri. Tandem autem inventa est via liberationis eorum subtili practica iuris, de qua longus esset tractatus conficiendus, et absoluti sunt Ulmenses a monachis et monachi ab eis, quibus Ulmenses aurum non modicum promptum dederunt, scilicet viginti quatuor milia florenorum, et omnia iura et bona in civitate Ulmensi et in circulo ad quatuor miliaria redemerunt, et hanc redemptionem concilium, papa et imperator ratificaverunt litteris et sigillis solemnissimis cum multorum principum subscriptione. Et hæc redemptio ad plenum facta est ævo nostro. et non multo post, propter varietatem causarum, si Ulmenses in duplo plus de auro dedissent, nihil effecissent. Unde abbati et monachis ingens accrevit contritio, quod tanti pretii bona pro tantillo vendidissent.",
         en="Als aber viele Güter verloren und Rechte eingebüßt waren, gingen den Mönchen die Augen auf, und sie fingen an, mit den Ulmern zu streiten, sie vor Gericht zu ziehen und neue, nutzlose Kosten zu machen; und so standen sie viele Jahre im Zwist. Darum waren die Ulmer vierzehn Jahre lang wegen der Mönche im päpstlichen Bann; und doch ließen sie sich nicht zu jenen Mönchen hinneigen, sondern bemühten sich beharrlich beim Papst und beim Kaiser, von ihnen befreit zu werden, was doch nach keinem Recht möglich schien. Endlich aber fand sich ein Weg zu ihrer Befreiung durch einen feinen Kunstgriff des Rechts, über den man eine lange Abhandlung schreiben müsste, und die Ulmer wurden von den Mönchen losgesprochen und die Mönche von ihnen; die Ulmer gaben ihnen nicht wenig Gold bar, nämlich vierundzwanzigtausend Gulden, und kauften alle Rechte und Güter in der Stadt Ulm und im Umkreis von vier Meilen los, und diesen Loskauf bestätigten das Konzil, der Papst und der Kaiser mit Briefen und feierlichsten Siegeln, unterschrieben von vielen Fürsten. Und dieser Loskauf ist zu unserer Zeit vollständig geschehen. Und nicht lange danach hätten die Ulmer wegen der Veränderung der Umstände nichts erreicht, auch wenn sie doppelt so viel Gold gegeben hätten. Darum kam den Abt und die Mönche große Reue an, dass sie so kostbare Güter um so wenig verkauft hatten.",
         note="Fabri nennt kein Jahr. Nach der neueren Landesbeschreibung (LEO-BW) war die Pfarrei 1327 dem Kloster Reichenau inkorporiert; das Recht, den Pfarrer vorzuschlagen, erwarb die Stadt schon 1383, sechs Jahre nach der Grundsteinlegung; 1434 brach Streit darüber aus, und 1446 erwarb die Stadt den ganzen Klosterbesitz mit allen Rechten um 25 000 Gulden. Fabri nennt 24 000. Die vierzehn Jahre Bann stehen nur bei ihm; welches Konzil bestätigte, sagt er nicht. Was er ‚feinen Kunstgriff des Rechts‘ nennt, bleibt bei ihm unerklärt. Die Bürger, die ihre Kirche ‚ohne Hilfe und Betteln‘ bauten (Grundstein [5]), bauten sie fast siebzig Jahre lang an einer Kirche, deren Patronat ihnen bis 1446 nicht ganz gehörte."),
    dict(n=6, titel="Der erste Pfarrer der Stadt", pg="27", lang="la",
         orig="Venerabilis dominus Heinricus Neithart, sacrorum canonum et legum doctor, modernus plebanus Ulmensis primus fuit, quem domini Ulmenses ordinario domino episcopo Constantiensi investiendum præsentarunt. Porro in his litibus Ulmensium cum monachis nobiles Sueviæ et civitatenses Ulmensibus auxilio et consilio erant, animabant et confortabant.",
         en="Der ehrwürdige Herr Heinrich Neithart, Doktor des Kirchenrechts und der Rechte, der jetzige Pfarrer von Ulm, war der erste, den die Herren von Ulm dem zuständigen Herrn Bischof von Konstanz zur Einsetzung vorschlugen. In diesen Streitigkeiten der Ulmer mit den Mönchen aber standen der Adel Schwabens und die Städter den Ulmern mit Hilfe und Rat bei, ermutigten und stärkten sie.",
         note="Mit dem Kauf ging das Patronat an den Rat: Er schlägt den Pfarrer vor, der Bischof setzt ihn ein. Der erste, den die Stadt so präsentierte, war 1488 noch im Amt, ein Doktor beider Rechte, also ein Jurist. Veesenmeyer verzeichnet die Schreibungen Nitthart, Neithardt, Neudhart, Nythart. Wie die Bürger als Patrone der Kirche auch die Altäre vergaben, sagt Fabri in seiner Beschreibung des Münsters (S. 39)."),
]

PFLEGER = [
    dict(n=1, titel="Die Rechner der Stadt", pg="131–132", lang="la",
         orig="Sunt etiam alii electi a consulatu civitatis thesaurarii, quos nominant ratiocinatores, quia recipiunt omnem pecuniam reipublicæ et datiis sive stüris, teloneis, censibus, angariis et punitionibus provenientem, et de ea rationem reddunt magistro stürarum sive datiarum, ad cuius manum multa civitatis pecunia offertur, qui supra dictis rationem reddit; sicque grandis cura et labor illis dominis incumbit tam in recipiendo quam in exponendo et singula conscribendo. Hi thesaurarii suo tempore pedes vadunt per totam civitatem, conscribentes vicos cum domibus omnibus et cum familiis per domos et familiarum personas singulas, ut sciant, quam contributionem recepturi sint, et ne possit fraude respublica pati damnum.",
         en="Es gibt auch andere, vom Rat der Stadt gewählte Schatzmeister, die man Rechner nennt, weil sie alles Geld des Gemeinwesens einnehmen, das aus Abgaben oder Steuern, Zöllen, Zinsen, Fronen und Strafen kommt, und darüber dem Steuermeister Rechenschaft ablegen, in dessen Hand viel Geld der Stadt gelangt und der den Obengenannten Rechenschaft gibt; und so liegt auf diesen Herren große Sorge und Mühe, im Einnehmen wie im Ausgeben und im Aufschreiben jedes Einzelnen. Diese Schatzmeister gehen zu ihrer Zeit zu Fuß durch die ganze Stadt und schreiben die Gassen mit allen Häusern auf, und in den Häusern die Familien und die einzelnen Personen der Familien, damit sie wissen, welchen Beitrag sie einnehmen werden, und damit das Gemeinwesen nicht durch Betrug Schaden leide.",
         note="Fabri beschreibt die Ämter der Stadt, wie er sie 1488 kannte. Die Rechner sind der Hintergrund für alles, was folgt: Wer die Kirche ‚mit den Mitteln der Stadt‘ bauen will (Grundstein [3]), muss wissen, wer in der Stadt wohnt und was er zahlen kann. Die späteren Abschriften glossieren am Rand ‚Stättrechner oder Stewrherren‘."),
    dict(n=2, titel="Die Pfleger der Pfarrkirche", pg="132", lang="la",
         orig="Alii de prætoribus eliguntur præsides thesaurorum ecclesiæ parochialis beatæ Virginis et disponunt de ædificiis. non enim parva illi ecclesiæ accidit substantia per vivos et morientes et per reditus.",
         en="Andere werden aus den Herren des Rats gewählt als Vorsteher der Schätze der Pfarrkirche der seligen Jungfrau, und sie verfügen über die Bauten. Denn dieser Kirche fällt kein kleines Vermögen zu, durch Lebende und Sterbende und durch Einkünfte.",
         note="Das sind ‚Unserer Frauen Pfleger‘, die Ulrich von Ensingen 1392 den Wochenlohn zahlten, ihn beaufsichtigten und ihm Urlaub geben konnten (Ensingen Ulm [1] und [2]). Sie werden aus dem Rat gewählt und ‚verfügen über die Bauten‘: Der Bauherr des Münsters ist nicht der Pfarrer und nicht der Baumeister, sondern der Rat durch seine Pfleger. ‚Per vivos et morientes‘ meint Gaben zu Lebzeiten und Vermächtnisse im Testament. Wen Fabri mit ‚prætores‘ meint, erklärt er nicht; die späteren Abschriften glossieren das Amt am Rand als ‚Pfarrkirchenbawpfleger‘."),
    dict(n=3, titel="Ein Beutel für Stadt, Kirche und Spital", pg="132", lang="la",
         orig="Alios præter illos eligit senatus, qui hospitali pauperum præsint, et rationem accipiant a magistro curiæ, et plebano hospitalario competentiam reddant, et de honesta ac possibili pauperum et advenarum provisione disponant. Est enim hospitale in Ulma abundans in possessionibus, villis, prædiis, censibus, reditibus, decimis et quotidianis eleemosynis, unde communiter dicitur, quod marsupium unum sit, in quod ponatur pecunia civitatis ex datiis, teloneis etc. accepta, et pecunia ecclesiæ beatæ Virginis et hospitalis.",
         en="Außer diesen wählt der Rat andere, die dem Spital der Armen vorstehen, vom Hofmeister des Spitals Rechenschaft empfangen, dem Spitalpfarrer seinen Unterhalt geben und über die ehrbare und mögliche Versorgung der Armen und Fremden verfügen. Denn das Spital in Ulm ist reich an Besitzungen, Dörfern, Gütern, Zinsen, Einkünften, Zehnten und täglichen Almosen; darum sagt man gemeinhin, es sei ein einziger Beutel, in den das Geld der Stadt aus Abgaben, Zöllen usw. gelegt werde und das Geld der Kirche der seligen Jungfrau und des Spitals.",
         note="‚Marsupium unum‘, ein Beutel: Fabri gibt wieder, was ‚man gemeinhin sagt‘, nicht was die Rechnungsbücher zeigen. Aber der Satz trifft die Sache: Stadt, Pfarrkirche und Spital wurden von Pflegern aus demselben Rat verwaltet. Kirchengeld war in Ulm Bürgergeld."),
    dict(n=4, titel="Die Pfleger der Armen", pg="132", lang="la",
         orig="Eligunt etiam aliquos magistros miserorum, qui non in hospitali, sed in domibus sunt, et hi experiuntur, quibus necesse sit mendicare hostiatim vel ante ecclesiarum fores, ne sub prætextu paupertatis otium mendicando sectentur.",
         en="Sie wählen auch einige Pfleger der Elenden, die nicht im Spital, sondern in ihren Häusern sind; und diese erkunden, wer es nötig hat, von Tür zu Tür oder vor den Kirchentüren zu betteln, damit nicht jemand unter dem Vorwand der Armut durch Betteln dem Müßiggang nachgehe.",
         note="Die Stadt, die ihre Kirche ‚ohne Betteln‘ baute (Grundstein [5]), regelte auch, wer in ihr betteln durfte: Die Pfleger prüften die Hausarmen, und nur wer es nötig hatte, durfte an den Türen und vor den Kirchen bitten. Die späteren Abschriften glossieren ‚Bürgerliche Allmoßkasten oder haußarmenpfleger‘."),
]

doc = {
    "id": "buergerkirche",
    "titel": "Die Kirche der Bürger: Patronat und Pfleger (Fabri 1488)",
    "autor": "Felix Fabri OP",
    "jahr": "1488",
    "sprache": "de",
    "orig_sprache": "la",
    "pg_label": "S.",
    "quelle": "Fratris Felicis Fabri Tractatus de civitate Ulmensi, hg. von Gustav Veesenmeyer (Bibliothek des Litterarischen Vereins in Stuttgart 186, Tübingen 1889), S. 24–27 und 131–132 (Internet Archive: fratrisfelicisf03fabrgoog). Übersetzung: eigene Arbeitsübersetzung.",
    "hinweis": "Zwei Stellen aus Fabris Traktat, am Seitenbild gelesen: wie die Stadt den Klöstern Bebenhausen und Reichenau ihre Rechte in Ulm abkaufte, bis sie selbst Patron ihrer Pfarrkirche war, und wie der Rat Pfleger über das Geld der Stadt, der Kirche, des Spitals und der Armen setzte. Fabri schrieb 1488 als Dominikaner und Lobredner seiner Stadt; dass die Ulmer im Streit mit den Mönchen gegen das Kirchenrecht handelten, sagt er selbst. Veesenmeyers Schreibung ist beibehalten, Auslassungen sind mit [...] bezeichnet. Die Übersetzung ist eigene Arbeit (CC0).",
    "sections": [
        {"id": "reichenau", "titel": "Der Loskauf von den Mönchen", "zk": "Reichenau",
         "blurb": "Die Klöster Bebenhausen und Reichenau besaßen Rechte in Ulm, Reichenau das Patronat der Pfarrkirche. Die Stadt leiht, kauft, wählt an den Mönchen vorbei, steht vierzehn Jahre im Bann und kauft sich schließlich für 24 000 Gulden los. Der erste Pfarrer, den die Stadt selbst vorschlägt, ist ein Jurist.",
         "units": REICHENAU},
        {"id": "pfleger", "titel": "Die Pfleger", "zk": "Pfleger",
         "blurb": "Der Rat wählt aus seiner Mitte die Rechner der Stadt, die Pfleger der Pfarrkirche, die Pfleger des Spitals und die Pfleger der Armen. ‚Man sagt gemeinhin, es sei ein einziger Beutel.‘",
         "units": PFLEGER},
    ],
}

OUT.write_text(json.dumps(doc, ensure_ascii=False, indent=1), encoding="utf-8")
print("buergerkirche.json:", sum(len(s["units"]) for s in doc["sections"]), "Einheiten")
