"""Baut data/fabri1488.json: Felix Fabri über das Münster, wie er es 1488 sah, und über die
fünf großen Werke der Stadt, unter denen der Kirchenbau eines war.

Latein: Fratris Felicis Fabri Tractatus de civitate Ulmensi, hg. von Gustav Veesenmeyer
(Bibliothek des Litterarischen Vereins in Stuttgart 186, Tübingen 1889), S. 39–42 und 140–144.
Internet Archive fratrisfelicisf03fabrgoog; im PDF dieser Aufnahme ist PDF-Seite = Druckseite + 20
für S. 39–42, aber Druckseite + 16 für S. 140–144 (gezählt ab 0). Am Seitenbild gelesen; die
maschinelle Texterkennung diente nur der Orientierung. Veesenmeyers Schreibung (æ, œ) und seine
Ergänzungen in eckigen Klammern sind beibehalten, seine Fußnotenzeichen weggelassen.
Übersetzung: eigene Arbeitsübersetzung (CC0).
"""
import json
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "data" / "fabri1488.json"

VORZUEGE = [
    dict(n=1, titel="Größer als jede Pfarrkirche", pg="39", lang="la",
         orig="Habet autem ecclesia hæc novem insignia singularia præ omnibus ecclesiis quæ in toto sunt Christianismo parochialibus. Primum, quod est ecclesia parochialis major quam quæcunque alia, non enim est nec collegialis nec episcopalis nec abbatialis, sed tantum simplex parochialis, major multis episcopalibus, et plerisque patriarchalibus solennior. Non tamen eam æquare audeo templo Sophiæ Constantinopoli, quod est toto orbe famosissimum, nongentis quondam sacerdotibus celebratum, mirabili opere, pretiosa materia constructum, quod iam heu spurcitiæ Mahometi subiacet; sed eadem ecclesia erat patriarchalis.",
         en="Diese Kirche aber hat neun besondere Vorzüge vor allen Pfarrkirchen, die es in der ganzen Christenheit gibt. Erstens: Sie ist als Pfarrkirche größer als jede andere; denn sie ist weder Stifts- noch Bischofs- noch Abteikirche, sondern nur eine einfache Pfarrkirche, größer als viele Bischofskirchen und feierlicher als die meisten Patriarchenkirchen. Doch wage ich nicht, sie der Sophienkirche in Konstantinopel gleichzustellen, die auf dem ganzen Erdkreis die berühmteste ist, in der einst neunhundert Priester Gottesdienst hielten, von wunderbarer Arbeit und aus kostbarem Stoff gebaut, die jetzt, ach, dem Unrat Mohammeds unterworfen ist; aber diese Kirche war ja eine Patriarchenkirche.",
         note="Fabri kündigt neun Vorzüge an und zählt dann zehn; Veesenmeyer verzeichnet eine Handschrift, die am Rand ebenfalls ‚IX habet insignia‘ vermerkt. Der Pilger Fabri hatte die Hagia Sophia nicht gesehen, wohl aber Jerusalem; seit 1453 war sie Moschee. Sein Wort über den Islam ist das gängige Schimpfwort seiner Zeit; es steht hier, weil es dasteht. Der Vergleich ist Fabris eigentliche Pointe: Die Ulmer Kirche ist keine Bischofskirche, nur eine Pfarrkirche, und doch eine der größten der Christenheit."),
    dict(n=2, titel="Das Licht", pg="39", lang="la",
         orig="Habet secundo illa ecclesia cunctis aliis maiorem pulchritudinem, non quidem in ornatu parietum aut structuris pavimentorum aut lapidum sculpturis aut picturis aut tabulaturis, sed in splendore luminis, in quo formalis consistit pulchritudo. vidi enim multas ecclesias opere et materia splendidiores, sed nullam adeo copioso lumine perfusam, nullam ita claram in omnibus angulis sicut istam; nec habet aliquem tenebrosum angulum aut opacum diverticulum aut fuliginosum habitaculum, sicut ecclesiæ grandes solent habere; nec capellas habet occultas, sed pervias et lucidas.",
         en="Zweitens hat diese Kirche eine größere Schönheit als alle anderen, zwar nicht im Schmuck der Wände oder im Bau der Fußböden oder in Bildhauerei, Malerei oder Tafelwerk, sondern im Glanz des Lichts, in dem die eigentliche Schönheit besteht. Denn ich habe viele Kirchen gesehen, die an Arbeit und Stoff prächtiger waren, aber keine, die so reich von Licht durchflutet, keine, die in allen Winkeln so hell war wie diese; sie hat keinen finsteren Winkel, keinen dunklen Seitengang und keinen verrußten Raum, wie große Kirchen sie zu haben pflegen; auch hat sie keine versteckten Kapellen, sondern offene und lichte.",
         note="Fabri gibt zu, dass andere Kirchen reicher geschmückt sind; er lobt, was die Ulmer Kirche hat, und das ist Licht. ‚Formalis pulchritudo‘, die Schönheit der Form, ist ein Begriff der Scholastik: Schönheit als Klarheit. Fabri war gelehrter Dominikaner und Pilger, der Jerusalem und den Sinai gesehen hatte; sein Vergleichsmaßstab ist weit."),
    dict(n=3, titel="Einundfünfzig Altäre, gestiftet von Ulmern", pg="39", lang="la",
         orig="Tertio altaribus numerosior cunctis parochialibus ecclesiis est illa: habet enim altaria quinquaginta unum, quæ omnia provisionem et competentiam habent, et dotata sunt non per principes aut nobiles aut per alienos, sed per ipsos incolas Ulmenses, et sicut patroni sunt ecclesiæ, sic et collatores omnium altarium sunt. Multa autem altaria sunt, quæ habent quinque, aliqua quatuor, aliqua tria beneficia. Et ex illo sequitur quartum, scilicet quod nulla parochia sola et simplex tantum habeat clerum in numero, quantum ulmensis ecclesia.",
         en="Drittens hat sie mehr Altäre als alle Pfarrkirchen: Denn sie hat einundfünfzig Altäre, die alle ihre Ausstattung und ihren Unterhalt haben, und gestiftet sind sie nicht von Fürsten oder Adligen oder von Fremden, sondern von den Ulmer Einwohnern selbst; und wie sie Patrone der Kirche sind, so vergeben sie auch alle Altäre. Viele Altäre aber haben fünf, einige vier, einige drei Pfründen. Und daraus folgt das Vierte, nämlich dass keine Pfarrei, die allein und einfach ist, so viele Geistliche hat wie die Ulmer Kirche.",
         note="Jeder Altar war eine Stiftung: Eine Familie oder Zunft gab Vermögen, aus dessen Ertrag ein Priester (eine ‚Pfründe‘, ‚beneficium‘) Messen las, oft für das Seelenheil der Stifter. Einundfünfzig Altäre mit bis zu fünf Pfründen bedeuten Dutzende Priester an einer einzigen Pfarrkirche. Dass die Ulmer ‚Patrone der Kirche‘ sind, setzt den Loskauf von Reichenau voraus (Reichenau [5] und [6]). Die Bilder und Altäre dieser Stiftungen nahm die Stadt 1531 wieder heraus."),
    dict(n=4, titel="Opferstock und Steine von weit her", pg="39–40", lang="la",
         orig="Quinto ecclesia ista est oblationibus ditior cunctis aliis. quantæ autem sint eius oblationes quæ quottidie per populum ulmensem offeruntur ad cippum vel pelvim pro eius structura, et ad altaria in argento et cera in domini plebani usum, qui scire voluerit, penset pretia laborantium artificum quottidie et adducentium a remotis locis lapides, quorum emptio et adductio incredibile pretium requirit, quia lapides illius ecclesiæ non de solo ulmensi, sed a remotis locis advehuntur; penset insuper domini plebani magnificum statum: non enim habet statum plebani aut canonici, sed statum ducit abundantis episcopi, quinque habens in curia adiutores et familiam copiosam, nec tamen aliam provisionem habet aut competentiam, nisi suorum subditorum spontaneas oblationes. Idcirco et communiter parochia illa virum habet aliquem egregium, generosum et doctum, dignum et meritum tanto beneficio.",
         en="Fünftens ist diese Kirche reicher an Opfergaben als alle anderen. Wie groß aber ihre Gaben sind, die täglich vom Ulmer Volk in den Opferstock oder das Becken für ihren Bau und an den Altären in Silber und Wachs zum Gebrauch des Herrn Pfarrers gegeben werden, das ermesse, wer es wissen will, an den Löhnen der Werkleute, die täglich arbeiten, und derer, die die Steine von fernen Orten heranbringen, deren Kauf und Fuhr einen unglaublichen Preis kostet, weil die Steine dieser Kirche nicht vom Ulmer Boden allein, sondern von fernen Orten herangeführt werden; er ermesse überdies den prächtigen Stand des Herrn Pfarrers: Denn er lebt nicht wie ein Pfarrer oder Kanoniker, sondern führt den Stand eines reichen Bischofs, mit fünf Gehilfen in seinem Hof und einem zahlreichen Hausstand, und hat doch keine andere Versorgung oder keinen anderen Unterhalt als die freiwilligen Gaben seiner Pfarrkinder. Darum hat die Pfarrei auch gewöhnlich einen hervorragenden, edlen und gelehrten Mann, würdig und verdient für eine so große Pfründe.",
         note="Hier steht, wie der Bau bezahlt wurde, und es ist nicht ‚ohne Betteln‘ im wörtlichen Sinn: Der Opferstock ‚für den Bau‘ stand in der Kirche, und das Volk gab täglich. Fabri meint mit ‚ohne Betteln‘ das Werben um fremde Gaben durch Ablässe und Pilger (Grundstein [5]); die eigenen Bürger gaben. Der Lohn der Werkleute und die Fracht der Steine sind die Kosten, die das Spiel als Baukasse führt. Der Pfarrer, der wie ein Bischof lebt, ist 1488 Heinrich Neithart (Reichenau [6])."),
    dict(n=5, titel="Fünfzehntausend zu Ostern", pg="40", lang="la",
         orig="Sextum est quod illa ecclesia cunctis aliis, audenter dico, in toto christianismo populosior, quamvis enim grandis sit, tamen festivis diebus est in condensis usque ad cornu altaris, et nisi essent monasteria, non posset capere populum. communi cursu tempore paschali communicantur ultra quindecim milia hominum in ea. Septimum, quod ex illo sequitur, est quod ipsa in sacramentorum usu est cunctis frugalior. Nam parochia non reperitur, in qua dietim tot pueri baptizentur, proportionabiliter enim omni die quinque pueri baptizantur in baptisterio illius ecclesiæ, quod regio decore exstat ornatum, et omnes baptizati notantur et inscribuntur. Similiter est de confessione et eucharistia, raro enim transit dies dominica quin præter missas sacerdotum sint communicantes vel gravidæ vel personæ infirmæ aut devotariæ.",
         en="Das Sechste ist, dass diese Kirche, ich sage es kühn, volkreicher ist als alle anderen in der ganzen Christenheit; denn obwohl sie groß ist, ist sie an Festtagen gedrängt voll bis an die Ecke des Altars, und wenn die Klöster nicht wären, könnte sie das Volk nicht fassen. Im gewöhnlichen Lauf kommunizieren in der Osterzeit mehr als fünfzehntausend Menschen in ihr. Das Siebente, das daraus folgt, ist, dass sie im Gebrauch der Sakramente ergiebiger ist als alle anderen. Denn es findet sich keine Pfarrei, in der täglich so viele Kinder getauft werden; im Durchschnitt werden nämlich jeden Tag fünf Kinder im Taufstein dieser Kirche getauft, der mit königlicher Zier geschmückt ist, und alle Getauften werden vermerkt und eingeschrieben. Ebenso ist es mit Beichte und Kommunion; denn selten vergeht ein Sonntag, an dem nicht außer den Messen der Priester Leute kommunizieren, Schwangere oder Kranke oder Fromme.",
         note="Fünfzehntausend Osterkommunikanten sind Fabris Zahl für die ganze Pfarrei; sie ist eine Schätzung, keine Zählung. ‚Frugalior‘ heißt im klassischen Latein ‚sparsamer‘; Fabri meint offenbar ‚fruchtbarer, ergiebiger‘. Dass die Getauften ‚vermerkt und eingeschrieben‘ werden, ist für 1488 bemerkenswert: ein Taufbuch, wie es die Kirche allgemein erst auf dem Konzil von Trient 1563 vorschrieb."),
    dict(n=6, titel="Gebeine und alte Bilder", pg="40–41", lang="la",
         orig="Octavum est consequens ad illa, quod excedit in sepultura. Habet enim parochia illa præter particularia cœmiteria duo grandia cœmiteria, unum extra ad omnes Sanctos, aliud intra iuxta parochiam, in quibus quottidie laborant pollinctores. Cœmiterium extra habet poliandrium adeo ossibus repletum, ac si omnis Suevia ossa suorum defunctorum in eum congereret. Dicunt autem sepelitores mortuorum, quod dum fodiunt ibi in altum, ubique attingunt firmissimos muros, puta fundamenta prioris ecclesiæ parochialis, quæ haud dubium gloriosa fuit, ut produnt artificiosæ sculpturæ de ea translatæ et insertæ muris illius modernæ ecclesiæ super ostia omnia, dempto ostio principali occidentali iuxta campanarum funes, quod habet novam sculpturam, cetera omnia sunt de antiqua parochia. In interiori vero cœmiterio, dum fodiunt, inveniunt ædificia subterranea et testudines vacuas et alia, quorum causa ignoratur. de quibus homines mirari solent, et cinerarium illius cœmiterii olim fuit cellarium monachorum Sancti Georgii sub capella sancti Valentini.",
         en="Das Achte folgt aus dem Vorigen: dass sie im Begräbnis alle übertrifft. Denn die Pfarrei hat außer den besonderen Friedhöfen zwei große Friedhöfe, einen draußen bei Allerheiligen, den anderen drinnen bei der Pfarrkirche, auf denen täglich die Totengräber arbeiten. Der Friedhof draußen hat ein Beinhaus, so voll von Gebeinen, als hätte ganz Schwaben die Gebeine seiner Toten darin zusammengetragen. Die Totengräber aber sagen, wenn sie dort in die Tiefe graben, stoßen sie überall auf sehr feste Mauern, nämlich die Fundamente der früheren Pfarrkirche, die ohne Zweifel herrlich war, wie die kunstvollen Bildwerke zeigen, die aus ihr herübergebracht und in die Mauern dieser jetzigen Kirche über allen Türen eingesetzt sind, außer der westlichen Haupttür bei den Glockenseilen, die ein neues Bildwerk hat; alle anderen stammen aus der alten Pfarrkirche. Auf dem inneren Friedhof aber finden sie beim Graben unterirdische Bauten und leere Gewölbe und anderes, dessen Ursprung man nicht kennt, worüber die Leute sich zu wundern pflegen; und das Beinhaus dieses Friedhofs war einst der Keller der Mönche von Sankt Georg unter der Valentinskapelle.",
         note="1377 trugen die Ulmer die alte Kirche ‚auf ihren Schultern‘ in die Stadt (Grundstein [3]); hier sagt Fabri, was davon im neuen Bau steckt: die Bildwerke über den Türen. Ob alle Portalskulpturen aus der alten Kirche stammen, wie Fabri sagt, prüft er nicht, und dieser Apparat auch nicht. Der Keller unter der Valentinskapelle ist der Weinkeller der Bebenhausener Mönche, den Fabri S. 24 beschreibt; die Stadt kaufte ihn mit ihren anderen Rechten (Reichenau [2]). Veesenmeyer verzeichnet für ‚cinerarium‘ auch die Lesart ‚carnarium‘, Beinhaus."),
    dict(n=7, titel="Die Lampen der alten Kirche", pg="41", lang="la",
         orig="Nonum singulare illius parochiæ est magnus affectus et dilectio parochianorum ad eam. Valde enim tam consulatus quam communitas illi afficiuntur ecclesiæ sicut suæ matri, et tam viventes quam morientes eam beneficiis honorant et decorant, perpetuas lampades ordinando et anniversaria statuendo. nam omnes lampades antiquæ ecclesiæ, quæ valde multæ dicuntur fuisse, in translatione eius abrogatæ fuerunt et proventus ex eis in structuram illius cesserunt, sic et anniversaria vetera extra constituta dimissa fuerunt in ecclesiæ novæ favorem.",
         en="Das Neunte, das diese Pfarrei auszeichnet, ist die große Zuneigung und Liebe der Pfarrkinder zu ihr. Denn sowohl der Rat als auch die Gemeinde hängen dieser Kirche sehr an wie ihrer Mutter, und Lebende wie Sterbende ehren und schmücken sie mit Wohltaten, indem sie ewige Lampen stiften und Jahrtage einsetzen. Denn alle Lampen der alten Kirche, deren es sehr viele gegeben haben soll, wurden bei ihrer Verlegung abgeschafft, und die Erträge aus ihnen gingen an den Bau der neuen; ebenso wurden die alten Jahrtage, die draußen gestiftet waren, zugunsten der neuen Kirche aufgegeben.",
         note="Eine ‚ewige Lampe‘ war eine Stiftung: Ein Kapital trug Zinsen, aus denen das Öl für ein Licht am Altar bezahlt wurde; ein ‚Jahrtag‘ war eine jährliche Messe für einen Verstorbenen. Fabri berichtet beiläufig, dass die Stadt 1377 diese Stiftungen der alten Kirche aufhob und ihre Erträge in den Neubau lenkte. Was die Stifter gewollt hatten, Licht und Gebet für ihre Toten, wurde zu Baugeld: auch so wurde ‚ohne Betteln‘ gebaut."),
    dict(n=8, titel="Eine Kirche, die den ganzen Tag offen steht", pg="41–42", lang="la",
         orig="Decimum et ultimum est, quod plebanus illius ecclesiæ magnis privilegiis gaudet in ecclesiæ favorem et suam non modicam utilitatem, nam interdicto a iure lato et posito non subiacet, quam cito nuntius ad episcopum Constantiensem missus extra civitatem venerit; ut puta si sacerdos percussus aut occisus fuerit, mox, ut iura disponunt, a divinis cessant, sed nuntio egresso contra Constantiam reassumunt divina officia. Item si cœmiterium vel ecclesia profanata fuerit, occulte eam potest plebanus per quandam aquam reconciliare. quod certe necessarium est, quia multitudo populi confusa est per varia, et stat ecclesia toto die aperta, per quam omnis homo transitum facit. est quoque in ea tumultus varius, maxime tamen cleri otiosi, qui ibi conventionem et collocutionem habet secundum quod in os venerit, per quod multum gloria illius ecclesiæ dehonestatur et populus valde scandalizatur. Sed et cœmiterium noctibus non clauditur, et timor est, imo indubitata experientia habet, quod multa committantur enormia persæpe, quibus locus sacer exsecratus et profanatus redditur. Ideo necesse est, plebanum aliquorum actuum episcopalium habere auctoritatem. Præcipue tamen maioribus privilegiis gaudet aliis plebanis in casibus episcopalibus et in pluribus aliis quæ transeo.",
         en="Das Zehnte und Letzte ist, dass der Pfarrer dieser Kirche große Vorrechte genießt, zugunsten der Kirche und zu seinem nicht geringen Nutzen: Denn dem Interdikt, das vom Recht selbst verhängt und auferlegt ist, unterliegt er nicht, sobald ein an den Bischof von Konstanz gesandter Bote aus der Stadt hinausgekommen ist; wenn etwa ein Priester geschlagen oder getötet worden ist, hört man sogleich, wie es das Recht bestimmt, mit dem Gottesdienst auf, aber sobald der Bote nach Konstanz aufgebrochen ist, nimmt man den Gottesdienst wieder auf. Ebenso kann der Pfarrer, wenn der Friedhof oder die Kirche entweiht worden ist, sie im Stillen durch ein bestimmtes Wasser wieder weihen. Das ist gewiss nötig, denn die Menge des Volkes ist auf vielerlei Weise durcheinander, und die Kirche steht den ganzen Tag offen, und jedermann geht durch sie hindurch. Auch ist in ihr allerlei Lärm, am meisten aber von müßigen Geistlichen, die dort zusammenkommen und miteinander reden, was ihnen gerade in den Mund kommt, wodurch die Ehre dieser Kirche sehr verunglimpft und das Volk sehr geärgert wird. Und der Friedhof wird nachts nicht geschlossen, und man fürchtet, ja man weiß aus unbezweifelter Erfahrung, dass dort sehr oft viele Ungeheuerlichkeiten begangen werden, durch die der heilige Ort verflucht und entweiht wird. Darum ist es nötig, dass der Pfarrer die Vollmacht zu einigen bischöflichen Handlungen hat. Vor allem aber genießt er vor anderen Pfarrern größere Vorrechte in bischöflichen Fällen und in mehreren anderen, die ich übergehe.",
         note="Das Lob kippt in eine Klage, und Fabri merkt es nicht oder will es nicht merken: Die Kirche ist Durchgang, Treffpunkt, Ort des Geredes, und gerade die überzähligen Geistlichen der vielen Pfründen ([3]) sind die lautesten. Ein Interdikt bedeutete, dass in der Stadt kein Gottesdienst gehalten wurde; die Ulmer Regel, dass ein Bote nach Konstanz genügt, um ihn wieder aufzunehmen, zeigt eine Stadt, die sich nicht lange ohne Messe sein lassen wollte. ‚Enormia‘, Ungeheuerlichkeiten auf dem nächtlichen Friedhof, nennt Fabri nicht genauer."),
    dict(n=9, titel="Nach der Weihe: die Mauern", pg="42", lang="la",
         orig="Igitur post ecclesiæ parochialis translationem et reædificationem et consecrationem regressi sunt Ulmenses ad suæ civitatis completionem et murorum per gyrum conclusionem, non enim erat adhuc undique clausa civitas. Ad consummationem autem operis omnes manus apposuerunt etiam optimates civitatis, et quo adhuc probiores fuerunt optimatibus Jerusalem, in cuius restaurationem non apposuerunt manus, ut habetur Nehem. 2.",
         en="Nach der Verlegung, dem Neubau und der Weihe der Pfarrkirche kehrten also die Ulmer zur Vollendung ihrer Stadt und zum Schluss der Mauern ringsum zurück; denn die Stadt war noch nicht überall geschlossen. Zur Vollendung des Werkes aber legten alle Hand an, auch die Vornehmen der Stadt, und darin waren sie noch besser als die Vornehmen Jerusalems, die an dessen Wiederaufbau nicht Hand anlegten, wie es bei Nehemia im zweiten Kapitel steht.",
         note="Fabri nennt die Weihe, aber kein Jahr; die neuere Literatur setzt sie auf 1405, als der Bau noch lange nicht fertig war. Die Stelle bei Nehemia ist Neh 3,5 (die Vornehmen von Tekoa ‚beugten ihren Nacken nicht zum Dienst‘); Fabri zitiert aus dem Gedächtnis. Wie beim Grundstein (Grundstein [4]) lässt er die Ersten der Stadt selbst Hand anlegen."),
]

WERKE = [
    dict(n=1, titel="Fünf Werke in fünfzig Jahren", pg="140", lang="la",
         orig="Et quod mirum dictu est, quinque magnifica et grandia opera aggressi sunt, quæ quasi uno et eodem tempore in spatio quinquaginta annorum perfecerunt, quæ si quis potens rex simul fecisset, procul dubio magnanimus et audax atque potens prædicatus fuisset. hæc quinque Ulmenses eodem tempore perfecerunt, sicut patebit. primum fuit civitatis munitio. secundum ecclesiæ beatæ Virginis fundatio. tertium prœliorum et obsidionum perpessio. quartum dominiorum in gyro emptio. quintum civitatis a monachis redemptio.",
         en="Und was wunderbar zu sagen ist: Sie nahmen fünf prächtige und große Werke in Angriff, die sie gleichsam zu ein und derselben Zeit, im Raum von fünfzig Jahren, vollbrachten; hätte ein mächtiger König sie zugleich getan, so wäre er ohne Zweifel als großmütig, kühn und mächtig gepriesen worden. Diese fünf vollbrachten die Ulmer zur selben Zeit, wie sich zeigen wird. Das erste war die Befestigung der Stadt, das zweite die Gründung der Kirche der seligen Jungfrau, das dritte das Erdulden von Kämpfen und Belagerungen, das vierte der Kauf der Herrschaften ringsum, das fünfte der Loskauf der Stadt von den Mönchen.",
         note="Fabris Rechnung zeigt, wogegen der Kirchenbau stand: Mauern, Kriege, Landkäufe und der Loskauf von der Reichenau zehrten an derselben Stadtkasse. Die ‚fünfzig Jahre‘ sind eine runde Zahl; der Loskauf, den er als fünftes Werk zählt, war erst 1446 abgeschlossen (Reichenau [5])."),
    dict(n=2, titel="Der Plan auf Pergament", pg="141", lang="la",
         orig="Aliud opus pariter cum isto inchoatum fuit, profecto grande et magnificum. quia enim timore obsidionis civitatis coacti urbem munierunt, ipsam etiam suam ecclesiam parochialem, quæ extra urbem erat, intus transtulerunt, ut securi in ecclesia esse possent, et templi mirabilis et magni fundamenta iecerunt, relinquentes nobis figuram charta depictam ecclesiæ, quam ipsi magnificis mentibus conceperant erigendam. quæ quidem charta multo pretiosius demonstrat templum, quam illud sit, in quo hodie laboramus, quia moderni parvifici non audent prosequi intentum antiquorum et quotidie multa spectantia ad pretiositatem et decorem structuræ detrahunt.",
         en="Ein anderes Werk wurde zugleich mit diesem begonnen, wahrlich groß und prächtig. Denn weil sie aus Furcht vor einer Belagerung der Stadt gezwungen die Stadt befestigten, verlegten sie auch ihre Pfarrkirche, die außerhalb der Stadt lag, hinein, um in der Kirche sicher sein zu können, und legten die Fundamente eines wunderbaren und großen Tempels; und sie hinterließen uns eine auf Pergament gezeichnete Gestalt der Kirche, die sie mit großem Sinn zu errichten geplant hatten. Dieses Pergament zeigt einen viel kostbareren Tempel, als der ist, an dem wir heute arbeiten, denn die Kleinmütigen von heute wagen nicht, der Absicht der Alten zu folgen, und nehmen täglich vieles weg, was zur Kostbarkeit und Zier des Baus gehört.",
         note="Die schärfste Stelle in Fabris Lob der Stadt: Die Gründer hinterließen einen Plan, und die Heutigen, die ‚parvifici‘, die Kleinmachenden, bleiben hinter ihm zurück und streichen am Schmuck. Fabri schreibt das 1488, vier Jahre bevor 1492 Steine aus dem Gewölbe fielen. ‚Charta‘ kann Papier oder Pergament heißen. Welchen Plan er meint, sagt er nicht; erhalten sind im Ulmer Museum Bauzeichnungen des 15. Jahrhunderts, darunter der Riss des Westturms, den die neuere Literatur Matthäus Böblinger zuschreibt (siehe die Tafeln). Für das Spiel ist der Satz die Grundspannung: der Plan der Alten gegen die Kasse der Lebenden."),
    dict(n=3, titel="Belagert, und man baut weiter", pg="141", lang="la",
         orig="His operibus instantes accessit aliud nimis importunum et grave. nam Ludwicus Bavarus, qui imperium invaserat, quem Papa cum omnibus sibi adhærentibus excommunicaverat, Ulmam venit, et cum Ulmenses nollent eum primo recipere, exercitu civitatem vallavit. intervenientibus autem quibusdam principibus eum receperunt, sicque ab eis recessit. Non multo post Henricus alter Bavarus Ludwici prædicti consanguineus, cui Papa imperium tradiderat, et cardinales, rex Bohemiæ et rex Franciæ eidem favebant, venit Ulmam cum multitudine Bavarorum, requirens Ulmenses, ut sibi adhærerent, sed nihil proficiens obsidionem solvit, et recessit, statimque post leprosus factus obiit. Deinde paucis interiectis annis Karolus quartus, contra Ludwicum Bavarum electus et confirmatus, etiam Ulmam gravi vallavit exercitu, sed sine effectu captionis civitatis recessit. In his obsidionibus nulla violentia fuit muris aut turribus civitatis Ulmensis illata, sed tantum postulatum ut amicitias inirent. Hæc omnia Ulmenses magis virtute et magnitudine animi ac prudentia quam bellis et armis vicerunt. In eo tempore duces Bavariæ, duces Austriæ, duces de Teck, comites de Wirtenberg diversis modis infestabant Ulmenses, ipsis infatigabiliter inceptis operibus mœniorum et turrium ac ecclesiæ beatæ Virginis persistentibus, sicut quondam filii Israel non curantes gentium impedimenta muros et turres Jerusalem et templum ædificaverunt, ut patet.",
         en="Während sie mit diesen Werken beschäftigt waren, kam etwas anderes hinzu, sehr ungelegen und schwer. Denn Ludwig der Bayer, der sich des Reiches bemächtigt hatte und den der Papst mit allen seinen Anhängern gebannt hatte, kam nach Ulm, und als die Ulmer ihn zuerst nicht aufnehmen wollten, umschloss er die Stadt mit einem Heer. Als aber einige Fürsten vermittelten, nahmen sie ihn auf, und so zog er von ihnen ab. Nicht lange danach kam Heinrich, ein anderer Bayer, ein Verwandter des genannten Ludwig, dem der Papst das Reich übertragen hatte und dem die Kardinäle, der König von Böhmen und der König von Frankreich gewogen waren, mit einer Menge Bayern nach Ulm und verlangte, dass die Ulmer ihm anhingen; aber da er nichts erreichte, hob er die Belagerung auf und zog ab, und bald danach wurde er aussätzig und starb. Dann, wenige Jahre später, umschloss auch Karl der Vierte, der gegen Ludwig den Bayern gewählt und bestätigt war, Ulm mit einem schweren Heer, zog aber ab, ohne die Stadt einzunehmen. Bei diesen Belagerungen wurde den Mauern und Türmen der Stadt Ulm keine Gewalt angetan, sondern nur verlangt, dass sie Freundschaft schlössen. Dies alles überwanden die Ulmer mehr durch Tugend, Großmut und Klugheit als durch Kriege und Waffen. Zu jener Zeit bedrängten die Herzöge von Bayern, die Herzöge von Österreich, die Herzöge von Teck und die Grafen von Württemberg die Ulmer auf verschiedene Weise, während sie unermüdlich bei den begonnenen Werken der Mauern und Türme und der Kirche der seligen Jungfrau blieben, so wie einst die Kinder Israels, ohne sich um die Hindernisse der Völker zu kümmern, die Mauern und Türme Jerusalems und den Tempel bauten, wie bekannt ist.",
         note="Fabris Folge der Belagerungen ist nicht verlässlich: Wer ‚Heinrich, der andere Bayer‘ sein soll, dem der Papst das Reich übertragen habe, ist unklar, und Ludwig der Bayer starb 1347, drei Jahrzehnte vor dem Grundstein. Die Belagerung durch Karl IV. setzt die neuere Literatur auf 1376, ein Jahr vor dem Grundstein (vgl. Grundstein [1]). Fabris Bild vom Bauen unter Belagerung stammt aus Nehemia 4, wo die Juden mit der einen Hand bauen und mit der anderen die Waffe halten."),
    dict(n=4, titel="Trotz schwerster Kosten", pg="142–143", lang="la",
         orig="Sic ergo non obstantibus expensis gravissimis, quas Ulmenses ædificando munitiones suæ civitatis faciebant et construendo ecclesiam ingentem beatæ Virginis, et se undique ab insidiantibus defendendo, magna emerunt dominia et nobilissimos comitatus.",
         en="So kauften also die Ulmer, ungeachtet der schwersten Kosten, die sie mit dem Bau der Befestigungen ihrer Stadt und dem Bau der gewaltigen Kirche der seligen Jungfrau und mit ihrer Verteidigung gegen Nachsteller von allen Seiten hatten, große Herrschaften und sehr edle Grafschaften.",
         note="Ein Satz, der zusammenfasst, was davor steht: der Kauf der Herrschaft Helfenstein mit Geislingen, der Grafschaft Albeck und anderer Herrschaften (S. 142, hier nicht abgedruckt). Unter diesen Käufen erzählt Fabri, die Grafen von Werdenberg hätten sich bei Ulmer Juden verschuldet und die Stadt habe die Grafschaft Albeck ‚aus den Händen der Juden‘ ausgelöst; er nennt sie dabei ‚infelices Judæi‘, die unglücklichen, und das Wort ist abschätzig gemeint. Die Kirche wurde gebaut, während die Stadt Land kaufte: Das Münster war nicht die einzige und nicht die teuerste Ausgabe."),
    dict(n=5, titel="Nicht ein Nagel blieb dem Abt", pg="143–144", lang="la",
         orig="Quintum et ultimum, quod etiam ea tempestate factum fuit magnæ difficultatis, quod tum domini Ulmenses virili animo aggressi sunt. Cum enim Ulmenses adhuc sub ditione monachorum Owiæ Magnæ essent, et in dies, ut prædictum est, monachi sua iura, bona et census ac telonea Ulmensibus venderent et debita magna contraherent, quæsiverunt Ulmenses vias qualiter totaliter a monachis liberari possent. quibus post multas Ulmensium excommunicationes inventis [sc. viis] auctoritate Papæ et ecclesiæ et imperatoris emerunt Ulmenses omnia iura abbatis Owiæ in Ulma et extra Ulmam ad quatuor miliaria cum omnibus bonis et attinentiis, solveruntque abbati in prompta pecunia viginti quatuor millia florenorum. et si contractus ille et ecclesiæ determinatio prolongata fuisset per mensem, vix recepisset abbas centum millia florenorum pro illis iam venditis iuribus tantis, quia illuminati fuerunt oculi eius. Abbas ergo accepta pecunia ita recessit ab Ulma, quod nec ungula in ea mansit quæ sua esset, cuius tamen fuerat ius patronatus ecclesiarum et altarium, omnes decimæ rerum, omnia telonea, pedagia et gwidagia, census, reditus de omni domo, foco et horto, de omni persona adulta, angariarum pecunia et violentiarum, pretium inspectionis vascanicarum, proventus ex libratione rerum in domo libr[at]arum, lucrarium [lucrorum] pars quasi in omni re et officiorum omnium provisio et munera quotidiana civium, quæ omnia Ulmenses emerunt usque ad unguem. Similiter iura, possessiones et bona abbatis in Bebahusen qui multa habuit in Ulma emerunt, ita ut non festucam ibi haberet. Ab aliis etiam sive religiosis sive secularibus, qui videbantur aliquid iuris in civitate habere, emerunt iura et civitatem liberam reddiderunt. nec est hodie civitas in imperio, audacter dico, liberior quam Ulma, in qua nullus princeps, nullus episcopus, nullus abbas quicquam habet, nisi sub censu communi civitatis.",
         en="Das fünfte und letzte, was ebenfalls zu jener Zeit geschah, war von großer Schwierigkeit, und die Herren von Ulm gingen es damals mit männlichem Mut an. Denn als die Ulmer noch unter der Herrschaft der Mönche der großen Reichenau standen und die Mönche, wie gesagt, Tag für Tag ihre Rechte, Güter, Zinsen und Zölle an die Ulmer verkauften und große Schulden machten, suchten die Ulmer Wege, wie sie von den Mönchen ganz befreit werden könnten. Als sie diese nach vielen Bannsprüchen gegen die Ulmer gefunden hatten, kauften die Ulmer mit der Vollmacht des Papstes, der Kirche und des Kaisers alle Rechte des Abtes der Reichenau in Ulm und außerhalb Ulms auf vier Meilen mit allen Gütern und Zugehörungen und zahlten dem Abt in barem Geld vierundzwanzigtausend Gulden. Und wäre dieser Vertrag und die Entscheidung der Kirche um einen Monat hinausgezögert worden, so hätte der Abt für diese so großen, nun verkauften Rechte kaum hunderttausend Gulden angenommen, denn ihm waren die Augen aufgegangen. Der Abt also nahm das Geld und zog so aus Ulm ab, dass nicht ein Fingernagel darin blieb, der sein gewesen wäre; und doch hatte ihm das Patronatsrecht über die Kirchen und Altäre gehört, alle Zehnten der Dinge, alle Zölle, Weg- und Geleitgelder, die Zinsen, die Abgaben von jedem Haus, Herd und Garten und von jeder erwachsenen Person, das Geld aus Fronen und Frevelbußen, die Gebühr für die Beschau der Fässer, die Erträge aus dem Wägen der Waren im Waaghaus, ein Anteil an den Gewinnen fast an jeder Sache, die Besetzung aller Ämter und die täglichen Gaben der Bürger; das alles kauften die Ulmer bis auf den Nagel. Ebenso kauften sie die Rechte, Besitzungen und Güter des Abtes von Bebenhausen, der vieles in Ulm hatte, so dass er dort nicht einen Strohhalm behielt. Auch von anderen, Geistlichen wie Weltlichen, die irgendein Recht in der Stadt zu haben schienen, kauften sie die Rechte und machten die Stadt frei. Und es gibt heute, ich sage es kühn, keine freiere Stadt im Reich als Ulm, in der kein Fürst, kein Bischof, kein Abt irgendetwas hat, außer unter der gemeinen Steuer der Stadt.",
         note="Fabris zweiter Bericht über den Loskauf, hundert Seiten nach dem ersten (Reichenau [5]), und er ist nicht derselbe: Dort hätten die Ulmer bald ‚auch mit dem doppelten Gold nichts erreicht‘, hier hätte der Abt einen Monat später ‚kaum hunderttausend Gulden‘ genommen. Aus vierzehn Jahren Bann werden ‚viele Bannsprüche‘. Die Liste zeigt, was ein Patronat und eine Stadtherrschaft wert waren: nicht nur das Recht, den Pfarrer zu wählen, sondern Zehnten, Zölle, Hausabgaben, Bußen und Ämter. ‚Vascanicæ‘ ist unsicher (Veesenmeyer verzeichnet die Lesarten ‚vestanicarum‘ und ‚vescanicarum‘); ‚Beschau der Fässer‘ ist eine Vermutung. Die neuere Literatur nennt 25 000 Gulden."),
]

doc = {
    "id": "fabri1488",
    "titel": "Fabris Münster, 1488",
    "autor": "Felix Fabri OP",
    "jahr": "1488",
    "sprache": "de",
    "orig_sprache": "la",
    "pg_label": "S.",
    "quelle": "Fratris Felicis Fabri Tractatus de civitate Ulmensi, hg. von Gustav Veesenmeyer (Bibliothek des Litterarischen Vereins in Stuttgart 186, Tübingen 1889), S. 39–42 und 140–144 (Internet Archive: fratrisfelicisf03fabrgoog). Übersetzung: eigene Arbeitsübersetzung.",
    "hinweis": "Zwei Stellen aus Fabris Traktat, am Seitenbild gelesen: seine Beschreibung der Pfarrkirche mit ihren ‚neun‘ Vorzügen, von denen er zehn aufzählt, und seine Liste der fünf großen Werke, die die Stadt zugleich unternahm, mit dem Satz über den Plan der Gründer, hinter dem die Heutigen zurückbleiben. Fabri schrieb 1488 als Dominikaner, Pilger und Lobredner seiner Stadt; seine Zahlen sind Schätzungen, seine Geschichte der Belagerungen ist nicht verlässlich. Veesenmeyers Schreibung ist beibehalten. Die Übersetzung ist eigene Arbeit (CC0).",
    "sections": [
        {"id": "vorzuege", "titel": "Die neun, die zehn Vorzüge der Kirche", "zk": "Vorzüge",
         "blurb": "Größer als jede Pfarrkirche, heller als alle, einundfünfzig Altäre von Ulmern gestiftet, ein Opferstock für den Bau und Steine von weit her, fünfzehntausend Kommunikanten zu Ostern, Gebeine und die Bildwerke der alten Kirche, die Lampen, deren Stiftungen in den Bau gingen, und eine Kirche, die den ganzen Tag offen steht und voller Lärm ist.",
         "units": VORZUEGE},
        {"id": "werke", "titel": "Die fünf Werke der Stadt", "zk": "Fünf Werke",
         "blurb": "Mauern, Kirche, Belagerungen, Landkäufe und der Loskauf von den Mönchen, ‚zu ein und derselben Zeit‘. Dazu der Plan der Gründer auf Pergament, der ‚einen viel kostbareren Tempel zeigt als den, an dem wir heute arbeiten‘.",
         "units": WERKE},
    ],
}

OUT.write_text(json.dumps(doc, ensure_ascii=False, indent=1), encoding="utf-8")
print("fabri1488.json:", sum(len(s["units"]) for s in doc["sections"]), "Einheiten")
